apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: infralytics-cicd
spec:
  allowCrossNamespaceImport: true
  instanceSelector: {}
  title: infralytics-cicd
  uid: infralytics-cicd
