apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: a855aea72584ca1344edcd7e03a74afa81394adb
  name: infralytics-cicd
spec:
  secretTemplates:
    - name: infralytics-mongodb-config
      stringData:
        config.json: ENC[AES256_GCM,data:eMnpPl7No1HdTw1VbS1WOqEJNIxsSX6ND2kOcUqiG0NaxkNUdoD61ePh50DZkTomYvuEP62Mx7gY1aTkiPr6JaXzalp5RSPaEfoedSla0EiyW9foj5sHp5F4Lxa/H4sXSTBeTcKBQK45HY0GlVv2YckrRIOGaDZQpzZ3yg17i2CThJtm+GTGR84WPUXF+32KlBzSfXoNMu7UOcQJTOPUNV9bM+zSuTvFAl94+zfdY5WaRdNp+X1Ic7/mOlkuWnwHlzjubcJaueCH6f/zhEN5Q281rZIGV1AsjKH7gArnMMyYd+fTkRvmWUnLdNbCVTZ+fhAzW0rC8VCuwQAgerS3U5DU4ryIGgsr+LNMJ5fnypYMl3OB5qwPpWGP5TXFni5SrL9Y7AIJFptjxe1NrHk2lRpKdCFb2n5zaq64w+zPAgYo+Zvg7fAll85qZfFIeuvoT+7BPPQoO5E=,iv:ptbZf0BUbA+miaMA4fACMBaoMefnZJ+8tUJB4VYR0zI=,tag:i5OF5ftQhUkwNN+QGU56cw==,type:str]
    - name: infralytics-minio-creds
      stringData:
        accessKey: ENC[AES256_GCM,data:QrMBeTEiHcOJ+n+fTbwGpstPyzk6Kg==,iv:7Z79vvU58p3H5lAAgk/lOll631B1Gh6LbwUY3y68LBI=,tag:fU53wDT1ri7ZXr+/uxV/tg==,type:str]
        secretKey: ENC[AES256_GCM,data:IRk+L0pxtXqwtn6Q2zJJAkxdVL19B8+M2AJninhcdmhd+/UtX92F/A==,iv:b3EfVeVuLQpOppLB2nohOqWwNbkcaUss6jAsDoEhfFQ=,tag:PO1G2V293rk6sBCTngA9xA==,type:str]
    - name: infralytics-mongodb-creds
      stringData:
        password: ENC[AES256_GCM,data:ON7Aoq8+Sms=,iv:TVEDVyMLn2DKowhQc1qmG/5Dt3qczOVVWyC9Gnvoyio=,tag:4onYWC+mw14mwEXqB2f9Rw==,type:str]
        username: ENC[AES256_GCM,data:bSn/uZbanSRWChc=,iv:gMVuNuD/hbacKWJgqHguk497JgwAvOvmtmfEwPmDM/c=,tag:VujhltrWvnu8uOcvhjXpPg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVFZzVWMzNDlraUhNQTNm
        bUIzRWlML0hxSnlqSTV4L21zYm5RVS92UjA0Cm8ydGJSckhiZk1XajhQT3JOaFdw
        UlZPa0l3MG9hMTFWUXB6bE5PRkdoWTgKLS0tIFAxV09PKzJhVEFleGpMVjRwbEdO
        bUVXUUZMZ2xSdU5MYUlwZ2xQZFJFbk0K0eTZIp/+KC/RUvC/UhICxFpGULyfbKmR
        Owb/hI41MqfLoy1L9ULCN11l6+rkeE/ektv9hMP1WFIsKEyw5coHNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:58:15Z"
  mac: ENC[AES256_GCM,data:Atw+rkBWrTYVizGvGqZnDha1I29wgQMeJbRSlKkIEwYfhnRACTSNAxoVcxEddSMJfgYlpE+h6A8/vKehg0CHAJKirSHrPI3eug8IkoRnhDLq5/ZSWxUOUPEJrWOZBTMcXb69OkeDPHEJt5VmakMjWnK8pzazkCg33kZcyiEDKHM=,iv:1MvzjXAdLQ8BuMpZ8ONiyyenJGkoR08fy0piZmT54Eg=,tag:wIrxbczbbO1JuMMsYMOR6w==,type:str]
  version: 3.13.3
