apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 6f81f60198e6368a3eab823827dc39820a8a7908
  name: infralytics-cicd
spec:
  secretTemplates:
    - name: infralytics-mongodb-config
      stringData:
        config.json: ENC[AES256_GCM,data:39NgPUG9Tp1TAK26VkqsBLBOvh6L7M49PoCumLp1wGzYu7XtBfUJIfnz7m5TNoKTsC2933NXGgs5MMTqdR52kjmsYdcg8ifZdCi6oNEyS3eXdEUJ6c2l4yVYeJ22vuaYXFnwbHts7E8BdkcYyCCPTBnqz/llpPMKOjcp/0NtxLQvTLdFHWh6WV8bXIDDLDMTClpd5iV7gCGvpJLAuZeZNXh5SNpIBiqt07u0fiplQBhStfFgldBMiCo/48NoLQhnFM639cjFZJ4SzQBw/9gzs8WxNk3d4cgkwgHIldDVyur0KcvSzFhtfXSDPO7hwtPQd0okl09FVp4oCP3Znx66FkSemQgOCe4Oev/h92ULgWfroQLGzCYckQ8PN3DzbtRmk8mkXk9+N2kO6zZbwJmPhBhA5xCpG8wQXmA7uJyOSthNomLZ6KajuzWr5vAlGUGGtbmJZxT79mF4ig==,iv:OhGfoOzTU1qvPKmbNtS8aTN0Sv4X6vk+YwsvAESDqUA=,tag:Y98TVO30AyOk/a4rjcq70w==,type:str]
    - name: infralytics-minio-creds
      stringData:
        accessKey: ENC[AES256_GCM,data:tiORCDb0GZkKmxaI293uVf6LXopzWA==,iv:S4YjRIDK5b7gmTC26pJFLZSLi548zcQ44n6B+pjn4TA=,tag:ByIGtwOypaVns3oHbq+ZNA==,type:str]
        secretKey: ENC[AES256_GCM,data:t7Pu61Cm89tUDuD0lRxVt46bVCY/SIiqd8Vi5NNjwK1zRGioKVqSnQ==,iv:GMpoDrj1uKTOnVyB7gnH7V5unb7xwz+egHWXhc8lGPo=,tag:nliV9nsF5TnfkqaAQjuKrw==,type:str]
    - name: infralytics-mongodb-creds
      stringData:
        password: ENC[AES256_GCM,data:w6t68z6qvVgVSg==,iv:9JepbPtHtIMOFqkUC6s853Kx+AuzfIgNldN+d1utKkY=,tag:dUu+DZ12DFtXM9YWP3z4IA==,type:str]
        username: ENC[AES256_GCM,data:/ft1I1C9+8rmZMY=,iv:Ck3gwXdSpdOod6oE887oF9FjOtGVY2dk0Ppleh0kuKQ=,tag:bZxDZo9+Avxk01c1wsF3Jw==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN1BndmNnUmlES0VqWWdR
        ekUrYmtta0UrblgwaTNKbzBEakU2UmxuOTBJCjExSUpvTytGUHRURFRJQ1hvZjlQ
        UjMvcFNENWRWaTNYZ0xDUndBcVJNVlUKLS0tIEVwWE1EdWtvYm9OUVBoSkdMTjMv
        YnJmL3ZRTW92S1dqdGZZNW9vV2ZkcTAKMAIVjbjbEzi03ChFqAWClvLuCpqhGSNZ
        Xr0VXYasXsSHYKJxndrQNLp2UBClLx0rj6JdVQ9pNk50iS1ztBwUPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:08Z"
  mac: ENC[AES256_GCM,data:JNlXgg1HIYtKhxx7x5KeMDES2/+P13mIhD//HH81WaRrfASxXJeZdyb8hCV0h3zur/S6R9YS4gRvmVLjEFB8iMDYzsDTukCxbj5EYPCDzdRmWK3mV0U+P/asY94giekvu3MoPKtKbcFwcEQ1J50hsUAtNT8rI1jULs8QqDJVx9k=,iv:90sGIRrI9YgqvGaiAf7jdpBpACR7v1C/aPsdsnlqBzk=,tag:hrVb+qCoUjqFU6H2gAgSnQ==,type:str]
  version: 3.13.3
