apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - files:
      - admin.hcl
      - infralytics-admin.hcl
      - infralytics-reader.hcl
    name: openbao-policies
    options:
      disableNameSuffixHash: true
kind: Kustomization
resources:
  - openbao-cert.yaml
  - openbao-setup-wf.yaml
  - openbao-sops.yaml
  - workflow-rbac.yaml
