apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 2b9ae817c43042e73cf4f769b2e907b03bbac2fb
  name: openbao
spec:
  secretTemplates:
    - name: openbao-unseal-keys
      stringData:
        unseal-20251208-1.key: ENC[AES256_GCM,data:s4yrgJG3EUn4OBGkXdMLvD+/RcinCgo8jMFfEifMAHm6bz1hCnwisX4ikMA=,iv:GFwtrKvyVvWGRVzmUvpZlMmxxl0HQYnOuCF5OrllHR0=,tag:IBQk9o4eHWAcNEc/OT0MHQ==,type:str]
        unseal-20251208-2.key: ENC[AES256_GCM,data:skaVF/g4d0uiCB9S5xWcD7Vf49KzTPxidgkDeBORmV36j65zq0gVVQZQhIU=,iv:DwLIcIxjR2pQLmlXTiHHdUA7xErPXCArh6HhJ+slg6M=,tag:L8D4KpjURyGaAWFgS2kGNQ==,type:str]
    - name: openbao-oidc
      stringData:
        OIDC_CLIENT_ID: ENC[AES256_GCM,data:qWfv02yf/g==,iv:TPBqH0U4iLjOBddeddxO9rPg7xUGUTTgHIdHLRHnfYc=,tag:9oc04eJMeF5srOr1fyN0yQ==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:YYhGDLUAcQ8ZLtQfRfjda1ijJqgFcnq4pn41wVYXkWk=,iv:BkTbMqlmGtWHCGZa+7zb8DBRosF65h+ByyB2aWyIHgE=,tag:3sXIXOIKcsv4wmuzHFq+Qg==,type:str]
        OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:28htUHAgz//7tA5BFVFi26FMks5j9WJfe2aspN1Y4/HcxxHFb24HriKu6is=,iv:gidDsz8Nr3/IXxLpUajIPg6CZG0CCqnAo55CCdwXsqo=,tag:FE1oIIRF8Pp0giCvnXtdhw==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbEpIdXFKSTB4Qlg1TFpv
        ZEhZQmhCK1c5b3U0OEV4ZlM0OEs3cWJCRDE4Cjh6SHBzTnA5S2tacDc0d083SWFy
        WVpZVU1mUFp3WnVGQ1BRcFZxaTdQVUEKLS0tIFBHL21aWS9QY3RPNTRhWThSSTdv
        MDBlZ0FVODU0TzdzbjVXUjVqNnh2MjAKv7PRMdtqgAwqMhR9PjVpgf/spCzCWmIA
        /7iaq+kKYYUz2Llx3aoNDPK4Co21v8y7MIt+YHkoknEP6z4/+A0FtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:eKyLMFehyWojaKU5T/CfzQjmBHGUhfySJ+MzZn1MFd6OtQTzXm17Qqd2Y4Pt+Vgjj4V7+X5vQfZgAtTfuSpqWkqJptoxYpoySUbmA4do2hgpaPKBbPSTGBEvJn0kioxwOZ3d9Birp7UTM7qiS1L/fjg4s2ebsV7SH26fY05s5pE=,iv:0yVTUmYY5Fo1l7OoBJxt5KOzXObZOOGBha0n1iHZyFs=,tag:hLKg7T19fX+ZAvEMO0lL6g==,type:str]
  version: 3.13.3
