apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 2b9ae817c43042e73cf4f769b2e907b03bbac2fb
  name: openbao
spec:
  secretTemplates:
    - name: openbao-unseal-keys
      stringData:
        unseal-20251208-1.key: ENC[AES256_GCM,data:BvP2rAlCxeOlhVVx+YOfFBeaQnwOfRA8lRtHgmrEnD1QOr1c/zs81LaXJsg=,iv:LeMRBUshkcr8TCFzUuzZidOAy47F/y3Q+C7gw8Y6qVA=,tag:v6inxqfVcAHgqbHzZJuvAg==,type:str]
        unseal-20251208-2.key: ENC[AES256_GCM,data:u75z7lgmPg3eJZX4ddNYSZDBgVBFaaFIck3UDpdEbFtNcvOH+W7S52a3EI0=,iv:rc50wWaUKHsX0gN5M+I5tznJvyUm+ujopf8TprlybCQ=,tag:i6+a7pURawXBenM6UCKFZA==,type:str]
    - name: openbao-oidc
      stringData:
        OIDC_CLIENT_ID: ENC[AES256_GCM,data:bPML3rkWkQ==,iv:vnyFvImyUkzEK1gS+QEMDTT+ekNzCP+t9VdweBLJyjI=,tag:EJdM87f/riypHcroC/Rcvw==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lJheHPwXIW3SghpUlXAzX79dIufidBWrQzjC/j91nAo=,iv:oAwhsHeRFH3addlQg/SQwLQzRqSkh+HLVuHTNP1GYls=,tag:q50Vsh6oy9HQQzTz4BSRWg==,type:str]
        OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:7NzdiP4Agk5njnofd/XbuU6ZOh57d8/GtepJ7Dx2MH4LdFzHAXd4q6I/jnQ=,iv:kqaHAY2zg95U/tRVZggCNsegDE1Ioq3GrH8tL458wB4=,tag:FL9xxP2ups2AcBOuDGu7Xg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMHBnalQraTNsV1k3TDJm
        ak9sQXgvaEJ4Sm1oN21sSzlTcHVDU1habkY4CkVzRmR1Ti9OOUpyUmE5TVRoMmVv
        bnB2QjY4RGxmUk9oc1l3S3VtMTRtYmMKLS0tIGhSV3paYUZydENld1kzRENZY0Vx
        NXhnUmxlMW9WcEtWQUliTHowVDYxd1EKGRX78S7VZwlRN/WVOtfsEw6xTtgWIzn/
        l13b9LAXkPp0a8MTmckCSKwV33s/u72o9W03WMTsxeTeacqNS00Mgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1umjsnzeel08tjeu5ye82v42suz5qhmcwm43x035gc75yyd8h5faqkmv4ew
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T12:41:38Z"
  mac: ENC[AES256_GCM,data:HPfM6H6Sf+3ABDVoxQus4dlqlTnfQ9LtkDP5HqrWo2Q5INrTx8lu72EOEYMNAjSgeA56ubOj2zcNqsW+tvXxj5FGljkQm5/u9ZxGGWEJhCO4iUGYGe6HhzCDYxAHhfyVcBOlYP5J0CR8TjvcC7NByap0vVMwNwH5kfes6biFqQk=,iv:qjNpYY8QQhsBQklXTfWJib0H1DXbqFVeOsOBMvksDOc=,tag:NWayvO9dRoQ45nOWMPZfnA==,type:str]
  version: 3.13.3
