apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 35c233666a4e74298c3f57a43971965baa25683e
  name: kube-prometheus-stack
spec:
  secretTemplates:
    - name: grafana-cfg-secret
      stringData:
        client_id: ENC[AES256_GCM,data:x4PTyYMN7w==,iv:CWxHFAXodXDVjAfjN4jJIGk3dmFNGcu3HtSCsI9JJp0=,tag:18Br+SyXmzBb/OmRsFRc9A==,type:str]
        client_secret: ENC[AES256_GCM,data:iwB008ztw6bJ25H6W90SoQZnYFDIMxuJL+FS3+ki/o8=,iv:cabBb4UsyIBrYqOHsgBPJoQGYhFB7TsO2TNkQHTpF9g=,tag:ToKxxGAckMWJqcxhRR2RpA==,type:str]
        smtp_password: ""
        smtp_username: ""
    - name: grafana-admin-secret
      stringData:
        admin-password: ENC[AES256_GCM,data:b/Cw2C8UvNxCcw==,iv:AoI3X+s2yub+AwfNYuD8LOmOmqgpNSAxSPU/8adwawY=,tag:WNGcnL7MKlDd1e6VIJ3O+g==,type:str]
        admin-user: ENC[AES256_GCM,data:JYTdnIY=,iv:n6W7G0yvn3zGMmvHASQPm8+wRogJUu8TmgIhxLi2n8s=,tag:2SGJnvrRA0ElsbqODw4TAQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d2FNQ1hKbndmbjRzRzVw
        dWVqWFdtQmNIZUczckE1NWJGbDM2bGJDZDFzCjdPQ1E1OS8xdG40elBRMTZsVWdh
        K3JDMTBRSjl1VEVEbjRTb3VrRW01T2MKLS0tIGI2OHV1NC9Qc0JDUEUycll1QnZK
        SDZFekU2WUIxTlNSeTNNWTFpUldtaDgKlR4ZQ4uDIYH9gmIcUbPbcWrbs58b81xj
        YJMPwv3+G9MPFhazXsy9KTOu/4DTswF25R9TQtFjPS3ZKzbylt/iDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1umjsnzeel08tjeu5ye82v42suz5qhmcwm43x035gc75yyd8h5faqkmv4ew
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T12:41:38Z"
  mac: ENC[AES256_GCM,data:FUGdlheS6R4tyOZZkTzw4SZZdJznu2BkgSbLxHOdZkO4PZQ03APySCe1noNj5nLu84KAC3CFtUIsBvwTm27GaY7Sx64BnYEeQp4TW7bPYB6jetutQyHlN6zpZMlNg/0ckILVKLbNGvTXMzJ5Ybg2NSlbWbZnrO2OFx+AamT4WBU=,iv:eAMxu8TXQa2N9gxLfu+i9DAD+a4g3PfypNBhNMVsv2k=,tag:km8zod6nZRKSg9p6l+tA+g==,type:str]
  version: 3.13.3
