apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 35c233666a4e74298c3f57a43971965baa25683e
  name: kube-prometheus-stack
spec:
  secretTemplates:
    - name: grafana-cfg-secret
      stringData:
        client_id: ENC[AES256_GCM,data:Lkdb1eqQ7Q==,iv:SjbkUR3WmZ9IhoHAeHhly/eoth7ViGrXW1J7ZbMPdQc=,tag:n+6JjSng0iIF6Um599nYHA==,type:str]
        client_secret: ENC[AES256_GCM,data:J3wRfHOjiqJQbNBQHLHfLhtvperYBJj/0HN9Rz6kSgU=,iv:4oGsaJipi58vPpBgN5mHZrdx7lMQIXN44WXhlY5ecbM=,tag:fPSTDB/RJ0XdS6nWbsIPtg==,type:str]
        smtp_password: ""
        smtp_username: ""
    - name: grafana-admin-secret
      stringData:
        admin-password: ENC[AES256_GCM,data:zYHbgQ8hH7FinA==,iv:+/zy32k7t03XhKBGSFDWo2tyghuIhbJrT9AVGEfXTs0=,tag:x5jFI1GgBV+9+rSZynULQQ==,type:str]
        admin-user: ENC[AES256_GCM,data:sXdmYys=,iv:YPlnElZwxO+ErRSdGeX64PEGb+IzwGLXl7GMWwrLFSk=,tag:k456ySP3Vs0sU94NvZ9bZw==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQlI4N2lQZTRvQXdjUlFv
        UUxwWEgzdmdLM21tQnhMQkZSSVFVQzM0bFRNCll5RTNmWEYxMDRpY2tKUjVaTkxq
        Z2tORC85bUF1YUdHMVBNR3k2VEZIbWMKLS0tIFpwbFBvUy9vQ1YwT0NtdFBBekF3
        Wk8vYUVvcVVKaks3YlRyLzFvNGtqU1UKr2A3652Y2OoOI9or8fMkxNC0dUdBX9eW
        JgTxj0UNFqRR2UbVH90PqMv/ktwA5u1Kl4OerC6044JBqi9NfUJtCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:aBLsI7xntGoI0yEtVB3qS2h0YYgLjsPbRvB4VLkTh9tfZrZqV2ZwgacPmqnW+RY+cWsfmpFdSQSqHPstvhFassiHbERLHnIAxQ1mJOkgVvQkNYbaXUXj851M1lBdUFJWd8hP/IumEBHsQfUmenSPfVA0M/KGyIDDKQ8Un3/JDwg=,iv:HhMLMYm7vUQQmXr3tZl8TihnE+n+NixNaXv85oX8HOE=,tag:NRsVSpbDFrvWo9TtJ4l7iw==,type:str]
  version: 3.13.3
