apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 3783a9e5642b326b1e72dabe0f24f16811ded66b
  name: gitea
spec:
  secretTemplates:
    - name: gitea-admin-creds
      stringData:
        password: ENC[AES256_GCM,data:dcK6mo5Wk0a0cw==,iv:ZcFZDZ1BkOqD9BMOI4JM1KIFaWDfJ+NNRqEIyR4cJdA=,tag:pypNnWo+zAjxYXik/oU/eA==,type:str]
        username: ENC[AES256_GCM,data:nHMmTDo=,iv:/WAs3iuFJOKNiyNdbsSHxtrw/OSDZWc/XWCZC6tsNJ0=,tag:4Duvj0GFXlTHbQMWcEG7aA==,type:str]
    - name: gitea-oauth-client
      stringData:
        key: ENC[AES256_GCM,data:u4A0Nt0=,iv:bo3LkLd33b5XwCK0S/toHTWZnaRzmYy/sJgYn9eULSc=,tag:MIdb8BMA5qQGxX/XmdIDsw==,type:str]
        secret: ENC[AES256_GCM,data:vps7MGQLM6djHwItoXTW+bR4BZ55UMxaQeJUwZY83NE=,iv:aQWp+ihP8MO7pRuWof3Z6spcMN3TG7R6rvXELlLAxGQ=,tag:aBnE3hXQkWZr9Wq46Ct6cA==,type:str]
    - name: gitea-smtp-creds
      stringData:
        password: ""
        username: ""
    - name: gitea-minio-creds
      stringData:
        accessKey: ENC[AES256_GCM,data:Pe48TV56jbE1sy+FVImfIQ==,iv:EPv+gLZU1kl3gSsGFVulph0CWW8wHEOh10pePvS3rio=,tag:sTnxGrGLVVOdoH7efUGNOg==,type:str]
        secretKey: ENC[AES256_GCM,data:3LZwAJvmvyfoHULZWsD5qXVwoMpFLjcgKnoSwVWTsHm2f5q9Xl/BbA==,iv:4gvtnj8TB+0D3eI2KM/qInvy79YugQ0qEfixYsujolE=,tag:HnaLAVhspm9ugIKbv8zcag==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbmZJNElsanNDUnVyOEVl
        a1JKKzFrc2VScGtjQnAycWlnOHA3UmI3U1ZrCm1XbnFUZi9hQW1XVGtwL3ZNbGpM
        SXlxM3c0ampaTXhERDI2b1I3OEFPOXcKLS0tIEkydFZBcjZJSHlzTnJ4Q2JtNXRk
        UHV5eTRLMkk4aE9LV0g0OCs4QXV5RXMKU2vIuWOfVlRTXeGGGJbrJEyuCXSeHH6f
        ViuHdOOOBhhiQNlDyqFREoY678KkdqlkCrLR4qOYJT1CNaHmVC240Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:ljDxYIp9T3dOiksp/QyL59dgQA77A+GxdCyHqKx5q0o6y0sCtkTpHWtCGjd1TlILZYgD6D1tw3xXzFb7EMlfJu+aZZ6juDfYDPJJYFNlzohNi9m/bjTtpt6sMso0rju5XX26NfLTiG2lzYa1ScEhC+/+33YKMmdiQ9JuePXjkxM=,iv:X5nCmsemXkHZ/kCe4krNCHhwrXYbJ1dWLEenXwkeBJk=,tag:OQCidiBWLijEmKSqb9tkZA==,type:str]
  version: 3.13.3
