apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      Create and push the materialized-views image.
  name: materialized-views-ci
spec:
  arguments:
    parameters:
      - name: repo
        value: https://github.com/DevalexLLC/infralytics-api
      - description: Specify the revision for non-interactive builds.
        name: revision
        value: development
      - description: Override the image tag if specified.
        name: image-tag
        value: ""
      - name: interactive
        value: "true"
  artifactGC:
    strategy: OnWorkflowCompletion
  entrypoint: main
  templates:
    - dag:
        tasks:
          - arguments:
              parameters:
                - name: repo
                  value: '{{workflow.parameters.repo}}'
            name: choose-revision
            templateRef:
              clusterScope: true
              name: choose-revision
              template: main
            when: '{{workflow.parameters.interactive}} == true'
          - arguments:
              parameters:
                - name: revision
                  value: |-
                    {{=
                      workflow.parameters.interactive == 'true'
                        ? tasks['choose-revision'].outputs.parameters.revision
                        : workflow.parameters.revision
                    }}
            depends: choose-revision
            name: checkout
            template: checkout
          - arguments:
              artifacts:
                - from: '{{tasks.checkout.outputs.artifacts.source}}'
                  name: source
              parameters:
                - name: revision
                  value: |-
                    {{=
                      workflow.parameters['image-tag'] != ''
                        ? workflow.parameters['image-tag']
                        : tasks.checkout.outputs.parameters.revision
                    }}
            depends: checkout
            name: build-push-image
            template: build-push-image
      name: main
    - container:
        args:
          - echo "Git Revision - $(git rev-parse --short HEAD)"
        command:
          - sh
          - -c
        image: alpine/git:v2.47.1
        name: main
      inputs:
        artifacts:
          - git:
              passwordSecret:
                key: GIT_TOKEN
                name: git-env
              repo: '{{workflow.parameters.repo}}'
              revision: '{{inputs.parameters.revision}}'
              usernameSecret:
                key: GIT_USER
                name: git-env
            name: source
            path: /git
        parameters:
          - name: revision
      name: checkout
      outputs:
        artifacts:
          - name: source
            path: /git
        parameters:
          - name: revision
            value: '{{inputs.parameters.revision}}'
    - container:
        args:
          - --dockerfile=Dockerfile
          - --context=.
          - --destination=harbor.pandathedog.com/library/materialized-views:{{inputs.parameters.revision}}
          - --destination=harbor.pandathedog.com/library/materialized-views:latest
          - --cache=false
          - --reproducible
          - --skip-tls-verify
        command:
          - executor
        image: gcr.io/kaniko-project/executor:v1.23.2
        name: main
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /kaniko/.docker
            name: docker-config
        workingDir: /workspace
      initContainers:
        - args:
            - |
              cat <<EOF >Dockerfile
              FROM mongo:8.2.3
              USER mongodb
              WORKDIR /materialized-views
              COPY --chown=mongodb:mongodb ./packages/mongodb-materialized-views .
              CMD ["/usr/bin/mongosh"]
              EOF
          command:
            - sh
            - -c
          image: busybox:1.37.0
          mirrorVolumeMounts: true
          name: setup
          workingDir: /workspace
      inputs:
        artifacts:
          - name: source
            path: /workspace
        parameters:
          - name: revision
      name: build-push-image
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
