apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: c97040a13d9c17a2a6daad36d0e2fedcaac5af07
  name: keycloak
spec:
  secretTemplates:
    - name: internal-clients
      stringData:
        argo: ENC[AES256_GCM,data:s+/bRzxh+KN+Vqz+jQitDFO9SXQ09FI2SPSJyPYRTQU=,iv:RGkHuEiRSFzOFSw8Ao6kOEbBU1KsUxymTQpXG0Wn/So=,tag:a3sOGTwiVOz5eDUatfFgRQ==,type:str]
        argocd: ENC[AES256_GCM,data:hRconMEhkQ+Mp3Gud9iBAgZanmAmfn8agy1RcoLgkO0=,iv:2Dj9hAUH9UyrYwQg9x7QeZH7PpxF03u4L7vBRM3CjpU=,tag:rT9lOpqgcErvQY7OGsmFAQ==,type:str]
        gitea: ENC[AES256_GCM,data:UehtqMACC+oqV3i0MG8U9ofsnm9GgjQ7j0Hcas2DC6c=,iv:eoD9f8oH5afFCf1h4QqNZ2SnRTMfZSClel4kGo5z3Gs=,tag:IuL3Ao9OGcJUhlIK3y1Ncg==,type:str]
        grafana: ENC[AES256_GCM,data:9vA+zPcZQSxhu/o353R6YHoCAA2YpVTavzLCn1BZHSU=,iv:bYQD3Dzw/VjIVqgPavJYvy7JRuSAIUQGDBzGaWUKwUw=,tag:h4JqgqZBGWgqVTTvaCuJ5Q==,type:str]
        harbor: ENC[AES256_GCM,data:D65/mnj33SERq3lCZjNdN9ZFvjBlacl8JglDnviipsA=,iv:XnlSbvtdXD0p2m1ilm/rWtfoPt2MRBhNajkKXbIBIaM=,tag:624dHDx2T1bbKAUtdw6OKA==,type:str]
        minio: ENC[AES256_GCM,data:JkE0IZoQyKmRotbAPjqHuO4FmOKDETDMJ3YK7/+nwS4=,iv:9R6ICSA9SjSiYGI5+IO9MNo6bVyGPXTE0UA4Y4wp/ro=,tag:rBTNdKTu0U+SAx6hCnC/VA==,type:str]
        openbao: ENC[AES256_GCM,data:/R+pR7Iwu/t1+mWDcJTIrK08Wgu24wxBXqNY5/YBNeg=,iv:3Dp0wD+PTCqYlduVHN/+qzN3lvkcC4DYJeOib4SLzzg=,tag:9KZLPHiALuqHte4ZyY9OsQ==,type:str]
        openwebui: ENC[AES256_GCM,data:hKOncRIgMkXlOdJTGiwrvraqAp2sYez2uVQ6DtO3D9Y=,iv:yx+Zwd8wk7JB6nlKoI54u+IvnwFt7oEatWZ61OOTqpQ=,tag:d568nOaEhTL9bnYswtrQ6w==,type:str]
        outline: ENC[AES256_GCM,data:KssKm1L29jNCOT+YMDbo78qnk4SyMA6kTwk+C3oPRGU=,iv:t+0e+tCnl47Z646IG6cYFYDHTomBV5Uu/i+kzlmNK9Y=,tag:9Ts1I22sDE+28MU4nQ+1Bw==,type:str]
    - name: public-clients
      stringData:
        impulse: ENC[AES256_GCM,data:8T1/tQx0hHWBwaraSB7uvP/jfCrbCWRcbqflMCSIUbY=,iv:Up77xAetoZnbswnAy5hpmRVBgmiYxIm3xMpqlc6vfiM=,tag:LYd0uCeBb6wix+xvk2phWg==,type:str]
    - name: keycloak-options
      stringData:
        base-url: ENC[AES256_GCM,data:wuzRxfVETm/JqMUgycC+4rmCbGK3O5D3sJS8QYinT8vH/gfvwEuo,iv:/vAA5uTsgFU7L8EJYOGm6eMuPQFuk7Th2qRSjZtYVeY=,tag:xGVx9V1xqBCxRaSA/smjUQ==,type:str]
        client-id: ENC[AES256_GCM,data:VQRX31o=,iv:MhaHp4XE0c1ZtpJARElMZeO8fmGNRGZW91YVcmNgMTE=,tag:Tzv14AMd0A0rZFGuJMtyUw==,type:str]
        client-secret: ENC[AES256_GCM,data:W2f0CdSpRpbS4c3cV5tTprcSaF97sW9sMl9Z0D1t8sKX8gln,iv:4xE6c36S1PGRBgtBKsoUq32zOaUz7ViNJJn5cqutsk0=,tag:cHT7ZUAhFl9gyLCWmTNCew==,type:str]
        log-console-level: ENC[AES256_GCM,data:y2vqYuA=,iv:fODldlh85k5v9AOsJ10v8j0K3aaKmfPjWZaolm88CEc=,tag:OzgpY8qRQ6ijHc25udeBtA==,type:str]
        log-console-output: ENC[AES256_GCM,data:orbsMA==,iv:KUXHBHE0JVH41ZdequYAdhOxQXtBS1F1J1+9KjLhpzc=,tag:pcjwt+X1rK0dI+psiMbBsA==,type:str]
        log-level: ENC[AES256_GCM,data:Gs8W4ADLGfxPAmgB854qtfc4ZlLfhMD66uNgLMQjffAGCwwLVV1LfoGMhcofyP/shXaeZRBdUS72o8YdEJ4cazGq3SUinR+WRQQtS/GAnv3idqqdgAE=,iv:RBZXu9YM0QK9v5m1sz6VQuwuYpQZ43173B4Aum/xYms=,tag:e1dIzCloFLXqaSO64tLX5Q==,type:str]
        oidc-url: ENC[AES256_GCM,data:1W401O2JHF+JgbMkDd+hu1kx/h9UyTREwNHOlTBLU/MlwwT7uQ==,iv:xYoubsnYlKUYmCxtRO6phgvd4BRxOcqB+BKHPKTeXsw=,tag:IjNb4ZAg3ZV/Nn3ulpUpSQ==,type:str]
        tenant-tag: ENC[AES256_GCM,data:817qoBvw5aEFtBAc,iv:8PExm0gNDgnLiFLpbuSCDVW4A9/SgcQ5lT9TDWfKxmA=,tag:aNF/k+K+lWRMaMRwHvGO0A==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbC9WZ3Nhc2hQMWxLcUl1
        a0lsT0ZzZ1luTlNhQWt2dTlHK1lycUNScEM0ClFsZktlNTRjb21FQ3FRY1ZqY1VL
        Q3IzRWJoMnBMd000dXd6Z25sOUdhSk0KLS0tIDB0NU01S1N1dFhnVjJBUHhOcklN
        bmVBdVZQTGswSjFRbnFZNjdyem1iMEkKZnUqI7MhMV7Ww+9fnW6EgTNsSir6bHH5
        nFA8CoVSVMpaiTSmhFvCa/8/pjAN6chFZk0L+ZOA4LXdSCh2gznKQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:08Z"
  mac: ENC[AES256_GCM,data:yQHX/7lMvGTmhFm9940HLumgn2G7cg7YGEIcTrL6sfg+6T3msQheSLquAhEGrQIqYypUo7zn0aVxKWBA9kSqwIg61f4wohPXuIx+qg2W1F9YV3bj9rf1Qc74YPpFDoLw/vsuYfNQ+IYBNh9GZSl+5u07/kUbhYMUaProtAn4teI=,iv:w9/aH/H7AaBL+C70LPXhxLQabAIygYgIzDbuVXAa4Sw=,tag:T2e8r49R4GmGuLHJ+JJ2XQ==,type:str]
  version: 3.13.3
