apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: c97040a13d9c17a2a6daad36d0e2fedcaac5af07
  name: keycloak
spec:
  secretTemplates:
    - name: internal-clients
      stringData:
        argo: ENC[AES256_GCM,data:4Q8pF+CLXLz8zL+4VcDZX7HraTeX6V7NO7g3vrISCUA=,iv:cbx1UdJYXGnRhWLPbt3SMqsG9TYHDJ64n/neeifPbL4=,tag:+msEakcRiGodaUnF+GayCg==,type:str]
        argocd: ENC[AES256_GCM,data:IiCIMpvtkdAn4Wf517YONeDBpXIP4WmKvGu2DkjWcAo=,iv:wnu+6Zzu4F6gjABvvAKECexmYBXNVnic5iQY16EJ1zs=,tag:af3x4qD1vHV9D8OMlWuOaA==,type:str]
        gitea: ENC[AES256_GCM,data:keD2jJbOvQsqhJ3YbmOa/a/hAxCXVtW4V8FW5Eawdxg=,iv:UitTOxbS0glSrqzOIDZrdmKbs2B34f1MtXruDMPFX/w=,tag:SwhFjHAYep1kaoj0h55pig==,type:str]
        grafana: ENC[AES256_GCM,data:QaA5accn3suzbfuDZta+1gyVjq8lm40JYj8/vEyFOTw=,iv:E7imXNO/Ia2yI4n4d8Jkjz0e0OGQX/SBjo43hJ3B/us=,tag:XHWG/f3rgAK0W4BjTbhlMw==,type:str]
        harbor: ENC[AES256_GCM,data:+SUV01vF7uqSuGoUOSmDHrtRjCksGoyNbLeUCap5+18=,iv:KTqUd2uRW2e4B5xBdW8MTYjHu4s/XMI5ecoQoQWV+w0=,tag:VXJ0RpvntyqiZClS7ENN2g==,type:str]
        minio: ENC[AES256_GCM,data:MxxJvG/9gXaudABmonlvHz33SMZ1GWkgn2gS7067QZQ=,iv:HY6jOYTJ3j2yLEUZHmYyBz+ZOlia9RR04+YwfAVB5Qc=,tag:RptWO6FsBixRdJZgeEwORA==,type:str]
        openbao: ENC[AES256_GCM,data:oMcYZAGBygTAlkhxQOsLCud2yW25HnKvJpMWwRq09gw=,iv:N9FC6PkOb/ptbIjwdJM/YONuh2XS8s5rqEJJRMPgfu0=,tag:xhiB8IWUp0azdfnTgY6nKg==,type:str]
        openwebui: ENC[AES256_GCM,data:lakDe9mH+vMcRqwwz8wksVz45l2iIGijUu4lfCzTOjQ=,iv:gpvtDvQg7OKsF9SYxUR5BLTbieQ8t2TxJouuY7MXds8=,tag:ADApDCLiNgdWf4nmpWgooA==,type:str]
        outline: ENC[AES256_GCM,data:8lCcwM0+SMcVLFjsZkuWjSIdEAfMt9VNAxv2oCCqg6A=,iv:FXBxmekZaQy+xwwzQWRlPQfVloMKY/s+vgfvCRO4i10=,tag:0OFzz9bhZmrt140EOwojKg==,type:str]
    - name: public-clients
      stringData:
        impulse: ENC[AES256_GCM,data:tR3Pt8pbs1nNZ7BVl1DGNycPGWhAWuuxdRj34bKrx3w=,iv:OW2VVQcU6BIbhAB+Zi3aVdkwztfjUxMk+5Zjw2/Q2S8=,tag:SEQCl+7uniGmaMxrcEM1fQ==,type:str]
    - name: keycloak-options
      stringData:
        base-url: ENC[AES256_GCM,data:ENctz7iMIwqni80bId85XxIign+cTqBUVDq9aHAHUEZDVoga7Ac3,iv:ldjW0dNWhZZmKKP5DH3kj+pqt9Y3w/fMz878b3+Hdyw=,tag:t12d/iTmgEXJc7IUCBSmLA==,type:str]
        client-id: ENC[AES256_GCM,data:kMVtJco=,iv:aKhQictKioBO9lXseuiQROhBM/n3YUTtxawwRA1oG1U=,tag:iXXkjEiMdI7Fl65oRpimxg==,type:str]
        client-secret: ENC[AES256_GCM,data:eTI3AnjtBZ/hoFr6prIIiMf+ND+kH0pOURdzAjC+8+XmVJyA,iv:qoX3SkBdilyAPaol6kmdg/HGl0qY4rBq9xYNVwWRPU4=,tag:IxOxOzZZXpHt++OyGH1qlg==,type:str]
        log-console-level: ENC[AES256_GCM,data:FY7gnBg=,iv:llLdy29YZE4CkfIAuo7f3TOMT4ldmnWoQ7ZaYFO70bc=,tag:5AS9BgZfpWG6RzhmvuvoUg==,type:str]
        log-console-output: ENC[AES256_GCM,data:BmlaOA==,iv:84LdKAmRUhMcM4z57hGhxhicVqNffOdfH2rScaDpWYs=,tag:jtVx/jGx3LbBng62K2GlZg==,type:str]
        log-level: ENC[AES256_GCM,data:cZDKWINvao2qOflbg++O6d0tVG4+etfE/49mQgrnVs1LHJEvOekWd/BEavXB05lyVjMWbS+qDBZK8zC+KEseTpLsRG0nSKMvkMXbgSqwm2u3l2jAYpE=,iv:r2BMh3ekQ71mzzkX2BqxFtY8tAWLa2+Pt7LqGBe/p3M=,tag:6zarCpRcERtWaF1kbCK7WA==,type:str]
        oidc-url: ENC[AES256_GCM,data:SxzNXQdIsG73HiP9AhlMPomJaCmdUrID3x4przXutOCMP417Fg==,iv:vDMEI42DPNinoSdh4FsSTgR6txYmbUW5+SVAKgzn4PM=,tag:mhAqrlO6eAUvAiFsJrCy4w==,type:str]
        tenant-tag: ENC[AES256_GCM,data:idnt3/yaM6dvqT4A,iv:Xgtxt2cXIXs051qH/J78lTm4eUDUcqOeYXyU/EqV79Q=,tag:J4enqh5ZbenjjbzR+ipl3w==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTjdadUZvekt1cDZpNkFt
        dEQ5MHUxR1BraHVxNzVodlZYM1BrRGpkdFNZClozOGNvc1djQnBPSWJrdXNxZHI4
        ZUR2Q2ZFVlBSYzFrS2JCTWJUbWExRWMKLS0tIGQ5WG94V1h2Mm1oaGtzclR2bU1p
        akZnaC9ZMUY3RU1rVXlrazdFTXV2VncKMpLx3xHJh0QyuoZD3arjcNyhUpX1l3bB
        QgUYSKeJBi3D4+8rvAuG6kmmhZWCAjnoBCnnK7lnF1lclsXYgYy02g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:Xdv/fFQ3jEPJmJGunENY5RLLjn+KAczx0HSqQ7JTE4/bSkncHFsqBx9MlvHd+DZMyyX0nUWWLn+inYxP9hQSzxWeZnGaU/Dvg3CN3HchlRglknxzIuFveXg7wbosDR5M5J3+A2OZ4fscpEo2E4xP6gDeoFgIbpyDgZn7uf7FA4g=,iv:3rzfK8hC4cMLSptKQFp2JipzBybOsbS6srkgDo5cxOo=,tag:/lpA/Qsy6JpkYRbtMxHxZw==,type:str]
  version: 3.13.3
