{
 "title": "collector-daily-report",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "query": {}
   },
   {
    "name": "site",
    "query": {}
   },
   {
    "name": "podName",
    "query": {
     "query": "{kubernetes.pod_namespace=\"infralytics-collectors\"} kubernetes.pod_labels.app.kubernetes.io/name:~\"^infralytics-collectors[./]$module.+$site$\""
    }
   },
   {
    "name": "type",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Collector Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 } },
  { "title": "Daily report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Modules status",
   "type": "table",
   "description": "Provides collector status from a module as the primary key.",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": \"daily\",\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"date\": {\r\n              \"$gte\": {\r\n                \"$date\": {\r\n                  \"$numberLong\": \"$__from\"\r\n                }\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$sort\": {\r\n            \"finish_time\": -1\r\n          }\r\n        },\r\n        {\r\n          \"$addFields\": {\r\n            \"runTime_ms\": {\r\n              \"$dateDiff\": {\r\n                \"startDate\": \"$start_time\",\r\n                \"endDate\": \"$finish_time\",\r\n                \"unit\": \"millisecond\"\r\n              }\r\n            },\r\n            \"errorSize\": {\r\n              \"$cond\": {\r\n                \"if\": {\r\n                  \"$gt\": [\r\n                    {\r\n                      \"$size\": \"$script_errors\"\r\n                    },\r\n                    0\r\n                  ]\r\n                },\r\n                \"then\": 1,\r\n                \"else\": 0\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$group\": {\r\n            \"_id\": \"$name\",\r\n            \"name\": {\r\n              \"$first\": \"$name\"\r\n            },\r\n            \"runTime_ms\": {\r\n              \"$first\": \"$runTime_ms\"\r\n            },\r\n            \"errorSize\": {\r\n              \"$first\": \"$errorSize\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          {\r\n            \"$arrayElemAt\": [\r\n              \"$task_col\",\r\n              0\r\n            ]\r\n          },\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"docCount\": 1,\r\n      \"module\": \"$metadata.module\",\r\n      \"site1\": \"$metadata.site\"\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"runTime_ms\": 1,\r\n      \"site\": \"$site1\",\r\n      \"module\": 1,\r\n      \"docCount\": {\r\n        \"$ifNull\": [\r\n          \"$docCount\",\r\n          1\r\n        ]\r\n      },\r\n      \"error_count\": {\r\n        \"$ifNull\": [\r\n          \"$errorSize\",\r\n          1\r\n        ]\r\n      }\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Type status",
   "type": "table",
   "description": "Provides collector status from a module's type as the primary key.",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 9 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": \"daily\",      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  \r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"date\": {\r\n              \"$gte\": {\r\n                \"$date\": {\r\n                  \"$numberLong\": \"$__from\"\r\n                }\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$sort\": {\r\n            \"finish_time\": -1\r\n          }\r\n        },\r\n        {\r\n          \"$addFields\": {\r\n            \"runTime_ms\": {\r\n              \"$dateDiff\": {\r\n                \"startDate\": \"$start_time\",\r\n                \"endDate\": \"$finish_time\",\r\n                \"unit\": \"millisecond\"\r\n              }\r\n            },\r\n            \"errorSize\": {\r\n              \"$cond\": {\r\n                \"if\": {\r\n                  \"$gt\": [\r\n                    {\r\n                      \"$size\": \"$script_errors\"\r\n                    },\r\n                    0\r\n                  ]\r\n                },\r\n                \"then\": 1,\r\n                \"else\": 0\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$group\": {\r\n            \"_id\": \"$name\",\r\n            \"name\": {\r\n              \"$first\": \"$name\"\r\n            },\r\n            \"runTime_ms\": {\r\n              \"$first\": \"$runTime_ms\"\r\n            },\r\n            \"errorSize\": {\r\n              \"$first\": \"$errorSize\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          {\r\n            \"$arrayElemAt\": [\r\n              \"$task_col\",\r\n              0\r\n            ]\r\n          },\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n\t\t\"docCount\": 1,\r\n      \"module\": \"$metadata.module\",\r\n\t  \"type\": \"$metadata.type\",\r\n      \"site1\": \"$metadata.site\"\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"runTime_ms\": 1,\r\n\t  \"type\":1,\r\n      \"site\": \"$site1\",\r\n      \"module\": 1,\r\n      \"docCount\": {\r\n        \"$ifNull\": [\r\n          \"$docCount\",\r\n          1\r\n        ]\r\n      },\r\n      \"error_count\": {\r\n        \"$ifNull\": [\r\n          \"$errorSize\",\r\n          1\r\n        ]\r\n      }\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Site Error Rate",
   "type": "bargauge",
   "description": "Displays error rate per site",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": \"daily\",      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  \r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"date\": {\r\n              \"$gte\": {\r\n                \"$date\": {\r\n                  \"$numberLong\": \"$__from\"\r\n                }\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$sort\": {\r\n            \"finish_time\": -1\r\n          }\r\n        },\r\n        {\r\n          \"$addFields\": {\r\n            \"errorSize\": {\r\n              \"$cond\": {\r\n                \"if\": {\r\n                  \"$gt\": [\r\n                    {\r\n                      \"$size\": \"$script_errors\"\r\n                    },\r\n                    0\r\n                  ]\r\n                },\r\n                \"then\": 1,\r\n                \"else\": 0\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$group\": {\r\n            \"_id\": \"$name\",\r\n            \"name\": {\r\n              \"$first\": \"$name\"\r\n            },\r\n            \"errorSize\": {\r\n              \"$first\": \"$errorSize\"\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          {\r\n            \"$arrayElemAt\": [\r\n              \"$task_col\",\r\n              0\r\n            ]\r\n          },\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n\t\t\"docCount\": 1,\r\n      \"module\": \"$metadata.module\",\r\n      \"site1\": \"$metadata.site\",\r\n      \"name\": \"$task\"\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"task\": \"$name\",\r\n      \"site\": \"$site1\",\r\n      \"module\": 1,\r\n      \"docCount\": {\r\n        \"$ifNull\": [\r\n          \"$docCount\",\r\n          1\r\n        ]\r\n      },\r\n      \"error_count\": {\r\n        \"$ifNull\": [\r\n          \"$errorSize\",\r\n          1\r\n        ]\r\n      }\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Last task errors",
   "type": "table",
   "description": "displays the last status of the task within the time range",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 19 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": \"daily\",\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  \r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n      {\r\n          \"$match\": {\r\n            \"date\": {\r\n                \"$gte\": {\r\n                \"$date\":\r\n                {\r\n                    \"$numberLong\":\"$__from\"\r\n                }\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$sort\": {\r\n            \"finish_time\": -1\r\n          }\r\n        },\r\n        {\r\n          \"$addFields\": {\r\n            \"runTime_ms\": {\r\n              \"$dateDiff\": {\r\n                \"startDate\": \"$start_time\",\r\n                \"endDate\": \"$finish_time\",\r\n                \"unit\": \"millisecond\"\r\n              }\r\n            }\r\n\t\t\t}\r\n\t\t\t},\r\n        {\r\n          \"$group\": {\r\n            \"_id\": \"$name\",\r\n            \"name\": {\r\n              \"$first\": \"$name\"\r\n            },\r\n            \"runTime_ms\": {\r\n              \"$first\": \"$runTime_ms\"\r\n            },\r\n            \"start_time\": {\r\n              \"$first\": \"$start_time\"\r\n            },\r\n            \"finish_time\": {\r\n              \"$first\": \"$finish_time\"\r\n            },\r\n            \"script_errors\": {\r\n              \"$first\": \"$script_errors\"\r\n            },\r\n            \"pod\": {\r\n              \"$first\": \"$pod\"\r\n            },\r\n            \"image\": {\r\n              \"$first\": \"$image\"\r\n            },\t\t\t\r\n            \"last_good\": {\r\n              \"$push\": {\r\n                  \"$cond\":[\r\n                    { \"$eq\": [{ \"$size\": \"$script_errors\" }, 0] },\r\n                    \"$finish_time\" ,\r\n                    \"$$REMOVE\"\r\n                ]\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$project\": {\r\n            \"_id\": 0,\r\n            \"name\": 1,\r\n            \"start_time\": 1,\r\n            \"pod\":1,\r\n            \"finish_time\": 1,\r\n            \"last_good\": {\"$first\":\"$last_good\"},\r\n            \"script_errors\": 1,\r\n            \"runTime_ms\": 1,\r\n\t\t\t\"image\": 1\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          {\r\n            \"$arrayElemAt\": [\r\n              \"$task_col\",\r\n              0\r\n            ]\r\n          },\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n {\r\n    \"$addFields\": {\r\n      \"module\": \"$metadata.module\",\r\n      \"type\": \"$metadata.type\",\r\n      \"site\": \"$metadata.site\",\r\n      \"name\": \"$task\",\r\n      \"script_errors\": {\r\n        \"$cond\":{\r\n           \"if\": { \"$eq\": [ \"$script_errors\", \"$null\" ] }, \"then\": [\"task was not run\"], \"else\": \"$script_errors\"\r\n        }\r\n      }\r\n    }\r\n  },\r\n {\r\n    \"$addFields\": {\r\n      \"cron\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$match\": {\"script_errors\": {\"$not\":{\"$size\":0}}}\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"run_parameters\":0,\r\n      \"task_col\":0,\r\n      \"metadata\":0,\r\n      \"task\":0,\r\n      \"run_type\":0,\r\n\t  \"category\":0\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "PodLog: ${podName}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "asc",
     "expr": "{kubernetes.pod_namespace=\"infralytics-collectors\",kubernetes.pod_name=~\"$podName\"}"
    }
   ]
  }
 ]
}