{
 "title": "collector-analytics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "site",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Statistics (30 day window)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Days since successful run",
   "type": "barchart",
   "description": "Displays the top 25 most stale tasks within the last 30 days",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\"daily\"]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"$expr\": {\r\n              \"$gte\": [\r\n                \"$date\",\r\n                {\r\n                  \"$dateSubtract\": {\r\n                    \"startDate\": {\r\n                      \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                      }\r\n                    },\r\n                    \"unit\": \"day\",\r\n                    \"amount\": 30\r\n                  }\r\n                }\r\n              ]\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$task_col\"\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"task_col.date\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$match\": {\r\n      \"task_col.error_count\": 0\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$task\",\r\n      \"latestChild\": {\r\n        \"$first\": \"$task_col\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"task\": \"$latestChild.name\",\r\n      \"date\": \"$latestChild.date\",\r\n      \"start_time\": \"$latestChild.start_time\",\r\n      \"finish_time\": \"$latestChild.finish_time\",\r\n      \"days_since_good\": {\r\n        \"$dateDiff\": {\r\n          \"startDate\": \"$latestChild.date\",\r\n          \"endDate\": \"$$NOW\",\r\n          \"unit\": \"day\"\r\n        }\r\n      }\r\n    }\r\n  },\r\n\r\n  {\r\n    \"$sort\":{\"days_since_good\":-1}\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Last successful run states",
   "type": "barchart",
   "description": "Displays count of tasks of their last run state.  30 day window",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\r\n          \"daily\"\r\n        ]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"$expr\": {\r\n              \"$gte\": [\r\n                \"$date\",\r\n                {\r\n                  \"$dateSubtract\": {\r\n                    \"startDate\": {\r\n                      \"$date\": {\r\n                        \"$numberLong\": \"$__to\"\r\n                      }\r\n                    },\r\n                    \"unit\": \"day\",\r\n                    \"amount\": 30\r\n                  }\r\n                }\r\n              ]\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$task_col\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"task_col.date\": -1\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$task\",\r\n      \"latestChild\": {\r\n        \"$firstN\": {\r\n          \"input\": \"$task_col\",\r\n          \"n\": 100000\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 1,\r\n      \"latestChild\": {\r\n        \"$first\": {\r\n          \"$filter\": {\r\n            \"input\": \"$latestChild\",\r\n            \"as\": \"tmp\",\r\n            \"cond\": {\r\n              \"$eq\": [\r\n                \"$$tmp.error_count\",\r\n                0\r\n              ]\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"task\": \"$_id\",\r\n      \"days_since_good\": {\r\n        \"$ifNull\": [\r\n          {\r\n            \"$dateDiff\": {\r\n              \"startDate\": \"$latestChild.date\",\r\n              \"endDate\": \"$$NOW\",\r\n              \"unit\": \"day\"\r\n            }\r\n          },\r\n          30\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"task\": \"$task\",\r\n      \"Last run failed\": {\r\n\r\n          \"$cond\": {\r\n            \"if\": {\r\n              \"$eq\": [\r\n                \"$days_since_good\",\r\n                1\r\n              ]\r\n            },\r\n            \"then\": 1,\r\n            \"else\": 0\r\n          }\r\n        \r\n      },\r\n      \"Warning\": {\r\n\r\n          \"$cond\": {\r\n            \"if\": {\r\n              \"$and\": [\r\n                {\r\n                  \"$gte\": [\r\n                    \"$days_since_good\",\r\n                    2\r\n                  ]\r\n                },\r\n                {\r\n                  \"$lte\": [\r\n                    \"$days_since_good\",\r\n                    6\r\n                  ]\r\n                }\r\n              ]\r\n            },\r\n            \"then\": 1,\r\n            \"else\": 0\r\n          \r\n        }\r\n      },\r\n      \"Critical\": {\r\n\r\n          \"$cond\": {\r\n            \"if\": {\r\n              \"$and\": [\r\n                {\r\n                  \"$gte\": [\r\n                    \"$days_since_good\",\r\n                    7\r\n                  ]\r\n                },\r\n                {\r\n                  \"$lte\": [\r\n                    \"$days_since_good\",\r\n                    13\r\n                  ]\r\n                }\r\n              ]\r\n            },\r\n            \"then\": 1,\r\n            \"else\": 0\r\n          }\r\n        \r\n      },\r\n      \"Severe\": {\r\n\r\n          \"$cond\": {\r\n            \"if\": {\r\n              \"$and\": [\r\n                {\r\n                  \"$gte\": [\r\n                    \"$days_since_good\",\r\n                    14\r\n                  ]\r\n                },\r\n                {\r\n                  \"$lte\": [\r\n                    \"$days_since_good\",\r\n                    29\r\n                  ]\r\n                }\r\n              ]\r\n            },\r\n            \"then\": 1,\r\n            \"else\": 0\r\n          }\r\n        \r\n      },\r\n      \"Catastrophic\": {\r\n\r\n          \"$cond\": {\r\n            \"if\": {\r\n              \"$and\": [\r\n                {\r\n                  \"$eq\": [\r\n                    \"$days_since_good\",\r\n                    30\r\n                  ]\r\n                }\r\n              ]\r\n            },\r\n            \"then\": 1,\r\n            \"else\": 0\r\n          }\r\n        }\r\n      \r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Success rate over time",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "collection": "task",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"type\": {\r\n        \"$regex\": \"$type\"\r\n      },\r\n      \"$expr\": {\r\n        \"$gte\": [\r\n          \"$date\",\r\n          {\r\n            \"$dateSubtract\": {\r\n              \"startDate\": {\r\n                \"$date\": {\r\n                  \"$numberLong\": \"$__to\"\r\n                }\r\n              },\r\n              \"unit\": \"day\",\r\n              \"amount\": 30\r\n            }\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$date\",\r\n      \"error_count\": {\r\n        \"$sum\": {\r\n          \"$cond\": [\r\n            {\r\n              \"$gt\": [\r\n                \"$error_count\",\r\n                0\r\n              ]\r\n            },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      },\r\n      \"count\": {\r\n        \"$sum\": {\r\n          \"$cond\": [\r\n            {\r\n              \"$eq\": [\r\n                \"$status\",\r\n                3\r\n              ]\r\n            },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      },\r\n      \"active\": {\r\n        \"$push\": \"$$ROOT\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"success\": \"$count\",\r\n      \"errors\": \"$error_count\"\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  { "title": "Aggregations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Top 15: Slowest mean",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\"daily\", \"ingests\"]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"$expr\": {\r\n              \"$gte\": [\r\n                \"$date\",\r\n                {\r\n                  \"$dateSubtract\": {\r\n                    \"startDate\": {\r\n                      \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                      }\r\n                    },\r\n                    \"unit\": \"day\",\r\n                    \"amount\": 1\r\n                  }\r\n                }\r\n              ]\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$sort\": {\r\n            \"finish_time\": -1\r\n          }\r\n        },\r\n        {\r\n          \"$project\": {\r\n            \"_id\": 0,\r\n            \"module\": 1,\r\n            \"date\": 1,\r\n            \"runtime_ms\": 1\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$task_col\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          \"$task_col\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"module\":1,\r\n      \"task\": 1,\r\n      \"date\": 1,\r\n      \"runtime_ms\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Top 15: Failure rate",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 6, "x": 8, "y": 16 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\"daily\"]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"date\": {\r\n              \"$gte\": {\r\n                \"$date\": {\r\n                  \"$numberLong\": \"$__from\"\r\n                }\r\n              }\r\n            }\r\n          }\r\n        },\r\n        {\r\n          \"$sort\": {\r\n            \"finish_time\": -1\r\n          }\r\n        },\r\n        {\r\n          \"$project\": {\r\n            \"_id\": 0,\r\n            \"name\": 1,\r\n            \"script_errors\": 1,\r\n\t\t\t\"error_count\": 1\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$task_col\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          \"$task_col\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"name\": \"$task\",\r\n      \"script_errors\": {\r\n        \"$cond\": {\r\n          \"if\": {\r\n            \"$eq\": [\r\n              \"$script_errors\",\r\n              \"$null\"\r\n            ]\r\n          },\r\n          \"then\": [\r\n            \"task was not run\"\r\n          ],\r\n          \"else\": \"$script_errors\"\r\n        }\r\n      },\r\n      \"has_errors\": {\r\n        \"$cond\": {\r\n          \"if\": {\r\n            \"$eq\": [\r\n              \"$error_count\",\r\n              0\r\n            ]\r\n          },\r\n          \"then\": 0,\r\n          \"else\": 1\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n\t\"$group\": {\r\n\t\t\"_id\": \"$name\",\r\n\t\t\"totalErrors\": {\"$sum\":\"$has_errors\"},\r\n\t\t\"count\": {\"$sum\":1}\r\n\t}\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"name\": \"$_id\",\r\n      \"totalErrors\": 1,\r\n      \"count\": 1,\r\n      \"failureRate\": {\r\n\t\t\"$divide\": [\"$totalErrors\",\"$count\"]\r\n\t  }\r\n    }\r\n  },\r\n  {\"$sort\":{\"failureRate\":-1}},\r\n  {\"$limit\":15}\r\n]"
    }
   ]
  },
  {
   "title": "Mongo operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"infralytics-collectors\"} _msg:~\"db action\" kubernetes.pod_labels.site:$site kubernetes.pod_labels.type:$type kubernetes.pod_labels.module:$module -log.metadata.database:=infralytics\n| rename log.metadata.* as *, kubernetes.pod_annotations.workflows.argoproj.io/node-name as collector\n| stats by (collector, action, log.timestamp.$date) avg(docs_affected) docs"
    }
   ]
  },
  {
   "title": "Top 10: Errors",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[    {\"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\"daily\", \"ingests\"]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }},\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"$and\": [{\r\n            \"$expr\": {\r\n              \"$gte\": [\r\n                \"$date\",\r\n                {\r\n                  \"$dateSubtract\": {\r\n                    \"startDate\": {\r\n                      \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                      }\r\n                    },\r\n                    \"unit\": \"day\",\r\n                    \"amount\": 1\r\n                  }\r\n                }\r\n              ]\r\n            }\r\n          },\r\n              {\r\n                \"$expr\": {\r\n                  \"$gt\": [\r\n                    {\r\n                      \"$size\": \"$script_errors\"\r\n                    },\r\n                    0\r\n                  ]\r\n                }\r\n              }\r\n            ]\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$task_col\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"script_errors\": \"$task_col.script_errors\"\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$script_errors\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"script_errors\": 1,\r\n      \"_id\": 0,\r\n      \"type\": \"$metadata.type\"\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  { "title": "Historical views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Task activity - Detailed",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[{\r\n    \"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\"daily\", \"ingests\"]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"$expr\": {\r\n              \"$gte\": [\r\n                \"$date\",\r\n                {\r\n                  \"$dateSubtract\": {\r\n                    \"startDate\": {\r\n                      \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                      }\r\n                    },\r\n                    \"unit\": \"day\",\r\n                    \"amount\": 1\r\n                  }\r\n                }\r\n              ]\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$task_col\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          \"$task_col\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$match\": {\r\n      \"start_time\": {\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"task\": 1,\r\n      \"final_status\":{\r\n        \"$add\": [\r\n          \"$error_count\",\r\n          \"$status\"\r\n        ]\r\n      },\r\n      \"start_time\": 1,\r\n      \"finish_time\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Task activity - Overview",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "collection": "task_definitions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"run_type\": {\r\n        \"$in\": [\r\n          \"daily\",\r\n          \"ingests\"\r\n        ]\r\n      },\r\n      \"metadata.site\": {\r\n        \"$regex\": \"$site\"\r\n      },\r\n      \"metadata.module\": {\r\n        \"$regex\": \"$module\"\r\n      },\r\n      \"metadata.type\": {\r\n        \"$regex\": \"$type\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"task\",\r\n      \"localField\": \"task\",\r\n      \"foreignField\": \"name\",\r\n      \"as\": \"task_col\",\r\n      \"pipeline\": [\r\n        {\r\n          \"$match\": {\r\n            \"$expr\": {\r\n              \"$gte\": [\r\n                \"$date\",\r\n                {\r\n                  \"$dateSubtract\": {\r\n                    \"startDate\": {\r\n                      \"$date\": {\r\n                        \"$numberLong\": \"$__from\"\r\n                      }\r\n                    },\r\n                    \"unit\": \"day\",\r\n                    \"amount\": 1\r\n                  }\r\n                }\r\n              ]\r\n            }\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": {\r\n      \"path\": \"$task_col\",\r\n      \"preserveNullAndEmptyArrays\": true\r\n    }\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          \"$task_col\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },  \r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"start_time_bucket\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$start_time\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 15\r\n          }\r\n        }\r\n      },\r\n      \"error_count\": {\r\n        \"$sum\": {\r\n          \"$cond\": [\r\n            {\r\n              \"$gt\": [\r\n                \"$error_count\",\r\n                0\r\n              ]\r\n            },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      },\r\n      \"count\": {\r\n        \"$sum\": {\r\n          \"$cond\": [\r\n            {\r\n              \"$eq\": [\r\n                \"$status\",\r\n                3\r\n              ]\r\n            },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": \"$_id.start_time_bucket\",\r\n      \"success\": \"$count\",\r\n      \"errors\": \"$error_count\"\r\n    }\r\n  }\r\n]"
    }
   ]
  }
 ]
}