{
 "title": "collector-db-health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "showID",
    "query": "true : asdasdasdasdasdas, false : _id"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Collector Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 } },
    {
     "title": "Run types",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
     "targets": [
      {
       "collection": "task_definitions",
       "queryLanguage": "json",
       "queryText": "[\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$run_type\",\r\n      \"count\": {\r\n        \"$sum\":1\r\n      }\r\n    }\r\n  }\r\n]"
      }
     ]
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index data",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "collection": "infralytics_data_stats",
       "queryLanguage": "json",
       "queryText": "[\r\n  {\r\n    \"$match\":{}\r\n  },\r\n  {\r\n    \"$unwind\":{\r\n      \"path\": \"$indexes\"\r\n    }\r\n  }\r\n]"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "index storage",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "collection": "infralytics_data_stats",
       "queryLanguage": "json",
       "queryText": "[\r\n  {\r\n    \"$project\":{\r\n      \"collection\":1,\r\n      \"count\": \"$count\",\r\n      \"collection_size\": \"$storage.size\",\r\n      \"storage\": {\r\n        \"$objectToArray\": \"$storage.indexSizes\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$storage\"\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          \"$storage\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\":{\r\n      \"_id\":0,\r\n      \"collection\":1,\r\n      \"count\":1,\r\n      \"index\": \"$k\",\r\n      \"collection_size\": 1,\r\n      \"index_size\": \"$v\"\r\n    }\r\n  }\r\n]"
      }
     ]
    },
    {
     "title": "index storage",
     "type": "barchart",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "collection": "infralytics_data_stats",
       "queryLanguage": "json",
       "queryText": "[\r\n  {\r\n    \"$project\":{\r\n      \"collection\":1,\r\n      \"count\": \"$count\",\r\n      \"totalIndexSize\": \"$storage.totalIndexSize\",\r\n      \"storage\": {\r\n        \"$objectToArray\": \"$storage.indexSizes\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$storage\"\r\n  },\r\n  {\r\n    \"$replaceRoot\": {\r\n      \"newRoot\": {\r\n        \"$mergeObjects\": [\r\n          \"$storage\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\":{\r\n      \"_id\":0,\r\n      \"collection\":1,\r\n      \"totalIndexSize\" :1,\r\n      \"count\":1,\r\n      \"index\": \"$k\",\r\n      \"storage\": \"$v\"\r\n    }\r\n  }\r\n]"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "read latency",
     "type": "trend",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "collection": "infralytics_data_stats",
       "queryLanguage": "json",
       "queryText": "[\r\n  {\r\n    \"$project\":{\r\n      \"collection\" : 1,\r\n      \"latency\": \"$latency.reads.histogram\",\r\n      \"_id\":0\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$latency\"\r\n  },\r\n  {\r\n    \"$replaceRoot\":{\r\n      \"newRoot\":{\r\n        \"$mergeObjects\": [\r\n          \"$latency\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\":{\"micros\":1}\r\n  },\r\n  {\r\n    \"$match\":{\r\n      \"micros\": {\r\n        \"$gte\": 250\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\":{\r\n      \"latency\":0\r\n    }\r\n  }\r\n]"
      }
     ]
    },
    {
     "title": "write latency",
     "type": "trend",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "collection": "infralytics_data_stats",
       "queryLanguage": "json",
       "queryText": "[\r\n  {\r\n    \"$project\":{\r\n      \"collection\" : 1,\r\n      \"latency\": \"$latency.writes.histogram\",\r\n      \"_id\":0\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$latency\"\r\n  },\r\n  {\r\n    \"$replaceRoot\":{\r\n      \"newRoot\":{\r\n        \"$mergeObjects\": [\r\n          \"$latency\",\r\n          \"$$ROOT\"\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\":{\"micros\":1}\r\n  },\r\n  {\r\n    \"$match\":{\r\n      \"micros\": {\r\n        \"$gte\": 250\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\":{\r\n      \"latency\":0\r\n    }\r\n  }\r\n]"
      }
     ]
    }
   ]
  }
 ]
}