{
 "title": "infralytics-api",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "infralytics" },
   {
    "name": "pod",
    "query": {
     "query": "{kubernetes.pod_namespace=\"$namespace\",kubernetes.container_name=~\".*-api$\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"$namespace\",kubernetes.container_name=~\"$pod\"}\n| count_uniq(log.requestId)"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"$namespace\",kubernetes.container_name=~\"$pod\"}\n| -log.statusCode:=\"\"\n| stats by (log.statusCode:100) count() hits"
    }
   ]
  },
  {
   "title": "Requests by User",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"$namespace\",kubernetes.container_name=~\"$pod\"}\n| not (log.requestId:=\"\" or log.user:=\"\")\n| stats by (log.user) count_uniq(log.requestId) requests\n| sort by (requests desc)"
    }
   ]
  },
  {
   "title": "Log Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=~\"$pod\"}\n| stats by (log.level) count()",
     "legendFormat": "{{log.level}}"
    }
   ]
  },
  {
   "title": "Slowest Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=~\"$pod\"}\n| not (log.user:=\"\" or log.elapsed:=\"\")\n| keep log.elapsed, log.requestId, log.timestamp, log.user\n| sort by (log.elapsed desc)\n| limit 10"
    }
   ]
  },
  {
   "title": "Slowest Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=~\"$pod\"}\n| not (log.user:=\"\" or log.elapsed:=\"\")\n| keep log.elapsed, log.requestId, log.user\n| first 10 by (log.elapsed desc)\n| join by (log.requestId) (\n    {kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=~\"$pod\"}\n    | \"log.label\":=\"Mongoose\"\n    | keep _msg, _time, log.query, log.query.*, log.requestId\n) inner\n| sort by (log.elapsed desc)"
    }
   ]
  }
 ]
}