apiVersion: v1
data:
  minio-repo: |
    s3:
      accessKeySecret:
        key: accessKey
        name: minio-creds
      bucket: workflows
      endpoint: s3.pandathedog.com
      insecure: false
      secretKeySecret:
        key: secretKey
        name: minio-creds
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: minio-repo
  name: artifact-repositories
