apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 5838c975d2633db60323483558a176a8aa695a31
  name: workflow-config
spec:
  secretTemplates:
    - name: git-env
      stringData:
        GIT_TOKEN: ""
        GIT_USER: ""
    - name: minio-creds
      stringData:
        accessKey: ENC[AES256_GCM,data:w2RgZiOV9Wn5ahd1XF0C,iv:MVa2e1d9hdTQDcrNFYlxQ/tFOEitLPbiNTQPOL0XXzc=,tag:hdH6f7Qs81b5YLd6xLmofw==,type:str]
        secretKey: ENC[AES256_GCM,data:hnLaLRQ8oKDBZK03RXVL49ujlXgls/Dz5pllHPeQaZjwkoxl+pYMRg==,iv:lSpNJPQKlNjamKQtNxKhwecHWkxbV8gESagZ2YG6ZUc=,tag:Gq5VUTIi4GFT6xE2BpLsJw==,type:str]
    - name: sonar-config
      stringData:
        SONAR_HOST_URL: ENC[AES256_GCM,data:KLk0977YzEAc4LYZJ0qHNDTPqmj/kIGPYmySeX0tCZ/f,iv:5ADJhz9aOyUkIL2Lum9l75lwh+Hcp7Z3+/91QH9oEKI=,tag:ly1l7f+gaaIzlAYvr2Q8lw==,type:str]
        SONAR_TOKEN: ""
    - name: docker-config
      stringData:
        config.json: ENC[AES256_GCM,data:RFEYq/24ip5JFK/TqnqfXrRNUJamq9k7eY5FswDjLClsxXMizjrBrhyU4U9x4G7WoGVObC1wIIsw3lZ/HKaeWpnEBWAFJOsivFWxVKL5bZKoxaOO1FzARlMlzOwWeus=,iv:uNMIGTSQg3cpbu/66D5tOtyEEZHK6aCaGqqo0rZWKmw=,tag:mTltFK3++EmuQCFVbjE2Fg==,type:str]
    - name: harbor-registry
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:QZOcK2m1cqmAlo77PW4OR+ZhkuFgqO+y3JjMheLqx4KBwpCPZoZgQLxHM+A8N0yJbrjC792RrE2WFIngjEP2mSMEzL/E+UpfUZLn4ScfZbIP2f1PmqrE/1vcA6WINGA=,iv:Tcze6vjOL6d+GtNRnmyBvLIoHrwz3FyG9gPha7Lm8fo=,tag:A9L+4S3/acyGovhcSLRXlQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaUEzVTFsTFZTQlNuN3pa
        cDhMTEpWcnIzQ094T0VwaHFRN203dm14SEh3ClhNVlNTYzA2Mm54cHQ3MnBiL0ZU
        WjMxaU1obTUvUlVWWlNuMUtyeVozU0UKLS0tIDUvblhEVmRPWWtaOUxpdER3SlZm
        VHAyN3J1OFI1Z3JjUUYvN3hzQkowNUEKwo/hucT0KwGZLPzt7tsmuuy39ABUjXQI
        SlH3TSENk8xhxOKBJmLZfRroN2EscFWgKFeiGDbxrUvn0ap4AobdOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:58:15Z"
  mac: ENC[AES256_GCM,data:F/CdYqH7ALgLPd47WaacopyLCg66YWEDygky8yqx8/1UJDF14eJ0rO14iwnQlJAdiEYtextirhNwCNl+J8JKOi170E5PJblH2umE7QteUwq2OfJZbXPS2FxU79B55CQHhmo1CDUCMmUqUVu7wBttuSnkNN0VyrWCHYi4x4Byk5M=,iv:t4U2HVnnXCv3wxY53B8v7ZzI0yu/lP8Xi4/A1nrdUUo=,tag:genFuI4/h9Hq3AJvc8lghg==,type:str]
  version: 3.13.3
