apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: c3f0f57d454b69b4b9998a80caa939d5dbb676e2
  name: workflow-config
spec:
  secretTemplates:
    - name: git-env
      stringData:
        GIT_TOKEN: ""
        GIT_USER: ""
    - name: minio-creds
      stringData:
        accessKey: ENC[AES256_GCM,data:HfloFw8pjNQK6X1+wifV,iv:G0imMko28lQXArBoNJOLTLBIGWD8dKYaIapKKGRNZfI=,tag:Ld5Btzb+IOISu2yA2FyHBw==,type:str]
        secretKey: ENC[AES256_GCM,data:glKyDfjeq0rPzlTVTkqBUvhAkbNGILl3ZPRWJE4myCGpDTXOJ60aGA==,iv:OCTnmhf41ESr4XCF3Q/v6ly+8hSGHgMdwwXjiTLLgNM=,tag:Oho1KrmuWxWn3WWJNMNslA==,type:str]
    - name: sonar-config
      stringData:
        SONAR_HOST_URL: ENC[AES256_GCM,data:Qp9yoWUqhcIzi5noY6iyMpgeYTqTwc5pZQht4NHlWn39,iv:35oQPkBXQXF8e2cCDOasi3SMN/+FKxvq42Ns4hPe78E=,tag:J48M00NX4WuuCxO0sZWr5g==,type:str]
        SONAR_TOKEN: ""
    - name: docker-config
      stringData:
        config.json: ENC[AES256_GCM,data:en5yioNAwEHrb1nTm/7Zfy9+/GuobmXLpY4o4XVZM+Wroyp6TIC4hw3bdv4x6oDipmvYDVV2bg1MsFov+y1veBX62TJEZOFkjxK6/XajJa1Y7ldrA/GcTS/jc5zJYcJCCxe4,iv:2kioSIdgkd6fknSh7bdKzXXsAkvx3swtR+9i86JIyUA=,tag:gMZWZC7EDqEiTOddVYFftw==,type:str]
    - name: harbor-registry
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:Z4SVM7qmKACsDPkZqLLN+O/Ia8mhdSMD3J6yVVopaEhZV2UGeuVrTPfsu6b7/gsSbf7+k8eJqH8bEPITh13ZPw5Xta6feV+UhowA7cbO4MMRIcy6A2BGXFmViw35Hpemv0DG,iv:hbwNMl3EZzmELa0JkRO7DZRemhqF9As5sJbh1nEUu6M=,tag:mitbljs1gr2f9XwSSUgApg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSzFkQUVaNTJ3cWoyV1N4
        eDdKMGZ6N0tkWjhMVUZhaldvdnB2QnpyTFhjCm80U3BWK3A0S1dvbHpod0w3WnU5
        dGNZRG9OMnl0Ujh3OUxncjJrVnRyd2MKLS0tIGtEdHpMd3UwQy9uV3drRW4vRkNS
        dmo4THlza0h3cDM3UmVEbUQ3N3FhMFEKJw6c3j+DRr8F0BdVDYlVPDCyOMjBSFe1
        h1eiXDcmRADgqHv5La7r7Ba0fEMlj23OaQtrayBAuo9/N4BSgMRXHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1umjsnzeel08tjeu5ye82v42suz5qhmcwm43x035gc75yyd8h5faqkmv4ew
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T12:41:38Z"
  mac: ENC[AES256_GCM,data:tspnPveQbGZ6te0RxK8dmI6ef4w128AZRW69Yfmy3UW4eoWdUPAhhM/GIvIOg3+9if+7G58sTqzGTb2Qb6gNuUnPhyD0VX2NU/MVo3jidBUpq4879mHuo80FUImITRsgIPXFNITZBkXyXG+EIuoVmL9iuecvKcNkH2Aqx1erx98=,iv:4I+mdJSrcxkIxctmUNy9pRyzNfxhLTdM9iFFd5QrGCc=,tag:TNgLaw1MtCEE9mjwQDU3aQ==,type:str]
  version: 3.13.3
