apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
    - chart: cert-manager
      helm:
        parameters:
          - name: crds.enabled
            value: "true"
      repoURL: https://charts.jetstack.io
      targetRevision: 1.20.3
    - path: cert-manager
      repoURL: https://github.com/andrew74b/dev-cluster
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
