apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: infralytics
spec:
  destination:
    name: in-cluster
    namespace: infralytics
  project: default
  source:
    path: infralytics
    repoURL: https://github.com/andrew74b/dev-cluster
    targetRevision: HEAD
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        linkerd.io/inject: enabled
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
