apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: mongodb-operator
spec:
  destination:
    name: in-cluster
    namespace: mongodb
  project: default
  source:
    chart: mongodb-kubernetes
    helm:
      valuesObject:
        community:
          mongodb:
            imageType: ubi9
            name: mongodb-community-server
            repo: quay.io/mongodb
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 1.8.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
