apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 94b93eb98746933b40dcf70c2d837a230e197c0a
  name: mongodb
spec:
  secretTemplates:
    - name: mongodb-infralytics-password
      stringData:
        password: ENC[AES256_GCM,data:s5Ip8RqlyGE=,iv:HEu8e1q/hjnbroR2svpWGN8UVHVo1ne3dbqNcIlFoUU=,tag:BtSTwVAuHJRu/ijorjQ7wA==,type:str]
    - name: mongodb-api-password
      stringData:
        password: ENC[AES256_GCM,data:HyRwyUSkysU=,iv:SOqgx0zef2ANm5JjfJUzbQh0qTVQZWellJIIe91NqRw=,tag:aZN99cABNUV2Ge1GRvp3Gw==,type:str]
    - name: mongodb-ingest-password
      stringData:
        password: ENC[AES256_GCM,data:LmM1BVpewPo=,iv:Vk31bLZsL3HCsxgVVoHC4VB8G6mrW/d2VSP7mukLnzQ=,tag:0mOH6yeRdy+nEr3k1ijdng==,type:str]
    - name: mongodb-smart-password
      stringData:
        password: ENC[AES256_GCM,data:8ot7MpMBJ2o=,iv:d4ZbZsPxyXyU+ygXq7yGd1lmlWBfTcVkrNs7NVXtsUs=,tag:1UMAe5qX+zuFpuFL3PjUvA==,type:str]
    - name: mongodb-collector-password
      stringData:
        password: ENC[AES256_GCM,data:mXIOHRLYIDI=,iv:uCAv3V5LgtXXjFKOTIDFmVfpZ6nyYhPIz1THcceHa/I=,tag:j/OQ0Bgj/D3xoXZWpK52jA==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZkRDZklpZnNXTnorTEdN
        dnkzc3R3bFlCRGZGWXdGT1NCOExobDhQK3lvCk4rQzNVUmJTODR3bTFiOFJ3UlZa
        UXRJbEl0L2d2UHMwcWp5aFdCTU9NSVUKLS0tIHM1TG1LMzlxUlNGRENyQytMS05s
        S2htN0pHOUFna1Q0Mmc4WXhpWHFqWE0Kbekl10en7tHncfHQ77I0kKtwWqweN9FA
        PHpH51ryRMHvsMK1sgct7CO31v9uM/CaNHVsSt8uKpb/INKvBlwsow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:58:15Z"
  mac: ENC[AES256_GCM,data:zZp+zSTl8oDyi0EyPfggF25GoM4LsFg1GRX2/Fzz4fkdPwNLYRnOoCdl2/0IPiC1TcdGTDxYcYdGigDB0WKH1JY7I1Lbi5eICzx5iqc0GgPt5Lvp9ZOsJva8ILFeVNjrriRx/XfYOf9pZ+B3xzxlFWQOhXztz5X+3TDcnMAMTpk=,iv:CmTGYzfW59k5a3gdmSGehYcWQynoEeLtrGIffVuAs4Y=,tag:vVX+FPvnfSsJ4s6bo6850g==,type:str]
  version: 3.13.3
