apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 8e30ec0bea0fac37c7160c2d275a2ac211ddb676
  name: argo-workflows
spec:
  secretTemplates:
    - name: argo-server-sso
      stringData:
        client-id: ENC[AES256_GCM,data:iw7Hb++dxq96jLnUYUc=,iv:HCDPmRgJ8EaqUc+QKgoYr+ALVy3gtMH8+GVp02LZKm0=,tag:nx5J0DVbrNJQftpjn5oxag==,type:str]
        client-secret: ENC[AES256_GCM,data:ilZFFEZ06DU6fGJxnqEtJzGJMkEqfpKbmkUOGZvKh7w=,iv:qCs+7tkjvsAqYW/rk+osU5qtC3mzUNnxiZkI83ujRvc=,tag:QjKS4p0LcmBMAQ8T3kKCrg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMenB3SEdubVZwZHF5VWZZ
        aUFJMFBGdU5DZVVUMldPZWkyQ05WUHFqaUVBCmpVTGdqUVd3WS9pdkZpOFZmdjZt
        dFVQL2I3Q0JNeVkwWERrQkFmZWJDWUUKLS0tIDJPQnQ4VHE5RmtIUTcrMzcwTVVW
        QXVsMVlDMEFqVmlNSEhGVk40NnVPT28KjzCkJGrIu5ruUGfag5Pn4M3Pmi7ZcMge
        ZbWvCANuavPzcDnMPs7Xed4XrhzizRJBqLzcDED8VhIHeH2+16EN4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:09Z"
  mac: ENC[AES256_GCM,data:MBeyC6E07Ukok4EOJ/HBYlvUFB1mPqv2J5b59LvirOaU/oAwhBz8ETjvPSsXjZnX/HE3NJ99nNu0B3LctAJFkHZGUhYH+PwFo6PKT2pMB9gnZD3ui/i8xVDekBDS9cYSoYE2UmZK9C4BsGsheaHMsesfsgljYkXmS6PxPV6ksaU=,iv:ooYeLC81O/gywQNdZjmYWbjVYXqMqE+YCdWG8RtWa5I=,tag:SxRjlTKvRgiw10zZpXULlA==,type:str]
  version: 3.13.3
