apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 8e30ec0bea0fac37c7160c2d275a2ac211ddb676
  name: argo-workflows
spec:
  secretTemplates:
    - name: argo-server-sso
      stringData:
        client-id: ENC[AES256_GCM,data:vgkAEY3H1sOh1m7Jad4=,iv:wDrrc3ukGRxzKoeNvVmADYPirVb6knpatbZ7zE7MBLk=,tag:v9dd7/fzrkUa3ycgS0NJPQ==,type:str]
        client-secret: ENC[AES256_GCM,data:2NBLbsC6Ln4YvLIa9CsdkmcluH70NE3JNcS6saSeknQ=,iv:Kb4bU9kNBHINl4gCPUq6AiWo0om18oY3EVhSuVfJnr8=,tag:33c6crTkAq9MX0K3rR1mEQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdUJ1UDc5VnE2WDd3YzAw
        QUZsUmp5THdIaTZUeFBFSmVGektlS0RsejA0Ckt5alhsaTFCL1BIRUsxNU1DKzQ3
        Rkh5MjlFQ1R5SnAycHNrNXpiT2VqRGMKLS0tIFFpL1F1OGZPZzRTT2pWaVM3WGt3
        V3pQR1Blb1FjamZEalVmVmxFdTFTVXMKsIzRvLZlxtsZPD1t0u6T4Lh5BMdL+dYo
        2vmqMgVdXyJOFeDAUzDPavzu4PoW3iveqnFHazOaGCja8RrbhXZdzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:5A4lVX6+osq3G4yc0/Sqm70Gx0OMwSk5kqhfMON1q8og7WMStqj8wGIsNhQAoDqcqwJfYnpwSgE5LTrdE2n3bFlUr9uFEHNXBV6P0JHYGoHLs6tKgU4rGJOL/Y1T3H4DdpdOoel6Jhd8Y8d2XuzL2wJXMsSsCRsyAtUK01gSrho=,iv:nS/vqIwAp8BzrpmGThOZ3/P51A847rqqUJ6ZBXj/tps=,tag:iVZxC8EHgUbEljmQ1dgJ2Q==,type:str]
  version: 3.13.3
