apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 4e4027f22d944614b2df0438e6358c6f6060b9b6
  name: harbor
spec:
  secretTemplates:
    - name: harbor-env
      stringData:
        CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:3D4cC2qv1AmJccJmMLFlC4UiaAiCRkGHJqMyIac4jBaG9p6nC8yq3vgEdizdpVEcKm/7yVxgLnDMLw0QqRwG3EshpztCMyDpGaSfIqMeEejZwWxBVE1r+WFGU7CIZg5V4l1fnW2if9UXMtcUs1KKj/ymrGTZI7uAsaFcqJrWgpG4nJynq14CAyWC3QniU2qKFKImeDqMpEy0HrfeLT/0X4EIGCHJhoq0ChNiDhYxk9OjWCWDvHJ8+QK93sMPDSziz5tN5nYyHY3i8iTxFU+BQvRIF6reiVObtNFRFbg7qurdRYgUJ6OGKioNzGLyDbmlswM03dVb3qHlSLuiArZ6cCtsW5M2eOOCgm5R29BJYKrc5IcFwGcH78JZ1wUfPAB13nzKJ48DE2baX4w24MpiJFR2vL1euN6gj2aiVejHdXHAK0ZD17LqHB3wHplQzJa2ITE97IvxSaGd6vjOHSiXuX2cUEa6KrgZO1ZLi8DrZwB2eygUuQmQ5wnUBqXHN9ZicBXBZ1qB3N1ozSrPI3dV/STWQFgCPoBQFGhhYUa+Pb9Yll4TAHMCDaBqJUcq1GpgZKX/Au2XOA==,iv:SuM4ISjDtchqUGtcpxAtgJV7o/Tos2qXKJ1SrucutSc=,tag:5VwHSBw/Zcyxj+BFrbpQgA==,type:str]
        CSRF_KEY: ENC[AES256_GCM,data:34yGXkWXHcohktznPM0yZdvYA2XYYtHJ9ZyJ/8qp7kg=,iv:5HCjjytvQh5qRFCHuJ/rBixrCshnCLYcADPqQLigsOk=,tag:MpcDehal0we8ZUeaymwgKw==,type:str]
        HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:rA6KLPsXHUTdyg==,iv:6jycGti/wLUp/4DLKABawkPKYPwvaahW4LNQBRTmvcY=,tag:OsxmhiuAsCYTIAR+0llsZw==,type:str]
        JOBSERVICE_SECRET: ENC[AES256_GCM,data:XWjLbknSl6J83U9YsGhwnQ==,iv:D9QvX/5+jMZDB2Rbm7LfaAf7jWB9fB1RUPR1TTPHqrE=,tag:tE/Nfdj8p4PERyCX79qyhQ==,type:str]
        REGISTRY_HTPASSWD: ENC[AES256_GCM,data:HNEq5ktYrqOcbH+0EtDANeUKxc+zaHJSGdBuAqzsJjdNJcwl471bVNzcovcp58G6pNmfehmKbD95CC9F03rEJoojk1dyVKExB48JpltDTgtS,iv:JDr5U5/a60/+FwSOuMOjrGpxm0A7fhtPvgY6ISllGaw=,tag:G7FeFj0uNxcBNyYcPtgJjQ==,type:str]
        REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:T2dwrVihzZUOVJ7Ioqo1Tw==,iv:4Rp4eU1vQ5pZSJyAFgI0r8INz8u3O9i2pK6D9omjg0g=,tag:4TLZh8keheBB08tZ/A264g==,type:str]
        REGISTRY_PASSWD: ENC[AES256_GCM,data:vwkggcCBzCk=,iv:DiR6BIJOuPLv04fI9FAT2zTut4MEh2GYkruR1egV4P8=,tag:XOMcmIJfzh+8AsuTF+BvBA==,type:str]
        secret: ENC[AES256_GCM,data:cSueYl5pmz5UTtLBJUsjmA==,iv:koMtyOfQVcHBsp15HQSO3wdxlDBOQ64tTZLY1bMU9gs=,tag:zojLxtc15HXxcF4cnmGDwQ==,type:str]
    - name: minio-creds
      stringData:
        REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:yo+U1xCJytIcet2NB9v0Pgo=,iv:YdLja+TP4xCQz++hv2nzcyY4CEwA4rzdCSEWxkmABK8=,tag:6CW63aiQcR1Ph+bpAvX0Mw==,type:str]
        REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:2LvaQ3+roVSJROuVGUYYUo65VDFjr+HMScUNPZvx/iNuc0NwWRgtLg==,iv:nz/CXqVdRN4i0IazCHGL57ywcEJVESI89ybD31s8AWc=,tag:yYHZlHMsKH0DmBJeBjQD1A==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3djcrMHlOREFYMXl4akwz
        TXRRSGwyZHU5YnZocS9vRW9Rd0szWStxSlQwCkwvU2xiSzc0d2tqTzhjSXpvY21I
        SEl4MlIzK3FjeTZvWEdueGQ0VW95M1UKLS0tIGVxUXZVNjRMUzZYSnFQUi8xaGRm
        d0UweVJUWGdNaXo2QnFsY0ZJc0Rac3cK/grZi/O3Bw6yc29ySg9JqDNmttvpuzUI
        WqffvPH3RdQ8SzvYbFjjRa1bGpFsxvjBBqwArdDLOGBDC/dcdY16nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:08Z"
  mac: ENC[AES256_GCM,data:sYQhRnIq6W5WA77hgZiJTzA+Fe32lEY0v19aNmyUaCye+QH9iyOT03QHKW7pyC8o+oL9J983DiDOKpmZGlh/fwzDGBLUY1hzmner+0NFSb284O3srj7joHWFUwjaY0PhWsVjTDmSALn8gPoLE0N9M3t5q8cZM/CGzGKpzOdMqHA=,iv:wxEEBjOP4XcEtrqU5xc/2B561RtI/muPbWqXhzCguRM=,tag:Me3ex1zfdM8Hy/o6tPR4dA==,type:str]
  version: 3.13.3
