apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 4e4027f22d944614b2df0438e6358c6f6060b9b6
  name: harbor
spec:
  secretTemplates:
    - name: harbor-env
      stringData:
        CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:o0PkgA2svIJMi5QwXKQJ88FPOhE40tdNcR3GJ1Jzpo47vGIMcq9kvP9aIJ/lpCOfWBtF/EPHt8pmBg62vSZYgYoHHY6gQOVsUXimIlveUHRF3pL3QrR5CggmyEBYic+Lfnh/0Tda31lFKwpdY6eTxbgYbNYoB68o2NUw9D1H1DrxG+k0IAa7mN5LvgWN/SDMMdbIYKW04p2ksK78agY1DcqQ/COL7uO/FrxYR5NRcD+H61cmfKc5RNmNIms6mHnfZEY1gKosqj9kU3wpCC7jgC3+ENO4BSskTu+WwkHIVN5SSO/5WuvEPT9LaHDr2ZX58+4kXA/rfUskidApg21AxWlfH5/kzVE9RSubaa5iSqd38MBZZKaLznkjtkQD89Kd+YCxqPSpy2qsURRX8qDEotTeNaINvWzUDjsdKpjlzjYBBDDFLPCaUZEsxQr2kjKdV6SBeRMG3zPfcbt77K0TvKoptMTJj0O3gceld/gB1dSQxre/kMPfmrr1fLFmQ5azcDVy5BcvPqitlua5Pvi5nkqAL5SlxKNtBSJiAuHk1dJgqkQ0o+Bg/Pl1tGKeDOuiqi96V0ZMAA==,iv:2EaAErTbX5wHLIQ9l7sn3+sDTwXt767nuE4stzrqwSc=,tag:S9vTlMHiQ5rBJjZodIGzOw==,type:str]
        CSRF_KEY: ENC[AES256_GCM,data:/yTsI4zMw3FuP5M14VysBTw846eKsd8ItBlye0Jrjt0=,iv:li31nnkTGZQ/joVbmIZf87/T0llZ68siTQl32mFtyG0=,tag:3qvsOalw5LQsrJ+oakiHHw==,type:str]
        HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:vHgv6GUAkevf+g==,iv:kc/9PplzD2iDQmOK8aRKN03/KGP+TrxUSbBPQihGSa0=,tag:xOk42nkVOcWTai1xDjnVug==,type:str]
        JOBSERVICE_SECRET: ENC[AES256_GCM,data:3eUoISiU4peh45vGT8FV/g==,iv:CNUK16vUlNdPyDjfpt5OgODNOrqb7UAJQ1oQvT/vNp0=,tag:hPgEwZdmjX6imzDDy5/CQA==,type:str]
        REGISTRY_HTPASSWD: ENC[AES256_GCM,data:gtdZpLVyu8cJfD8B+L/IeHLP5dXHIrskCFK7vJ8PMrkdPnkkSf5XctCtbNQSR5eScu307amwOEYtnFvmlP7SRaPJEhlkPl56SX13zAwcs7xD,iv:T/te9rs6NlrfKsDpsE6Iu84SvM/Zoz6LiXWSaXWMb98=,tag:fn7nn7Yh6wupmA3B7CVr5A==,type:str]
        REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:p4gY5RsnX+4bnjdMAJ+Lxg==,iv:ceuveI5YxQeids2K+Nb2PvPC/irLe01g8aNO7TDooJU=,tag:j8aicC8rEmDJe3NX7m9Nzw==,type:str]
        REGISTRY_PASSWD: ENC[AES256_GCM,data:luIv9ZIldKQ=,iv:9gvlEidriQu6YDS2NpPYBQhNjfjt/DZQbHbFXs3/IuQ=,tag:porQUnYILiKnBbryDwTCZg==,type:str]
        secret: ENC[AES256_GCM,data:drJYhPAYx5iLN42QhcIRPw==,iv:TADyalpJ2Urs5oFf0ojEQzpcCkknn860h0ZBjwppTOs=,tag:ivHVssYhJtwBmKjM55igTQ==,type:str]
    - name: minio-creds
      stringData:
        REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:w6umKs6L5tQoohyKL0DtHfo=,iv:n8JyJ5ikxA0FOFHPIgSFFhPyZwCnCCHZe0P8Q4MwbGE=,tag:JqS1oOgrGdUndA0jLaPjAA==,type:str]
        REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:dzIWNijt0zrneORoVdqNeuVOmlOkf4HDhSIbdVe/pz3ChseCZ1SWIQ==,iv:FUPO8U7tXDgQeeTsAa6lYvwWJx/lYEvo7Cc9OvmJySQ=,tag:HXOgGlzIVJbkfA6Bt1UMTQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY3hPbXk4cXNFOE5na09j
        cThWbWZTcXRTMWVoZGFUeVZQK2ZzNCtCWWk4Cm5sT1FCNFlzRCtxT2RWQitibHpj
        aVNtd1UxY3FoU0JTdUF1d3grYUVINXcKLS0tIFpFUndEOFRzZUhQSEpPYnhvSWR4
        YXpZNWh2My94aXZhNTJpWGtpSW5WbVUKNiZms1s8oROHBQyMW9u1cvtzHLbzGIoN
        ZKwuby869xSxri2k3b0e1rAT2Sqy/aW0swAsQHRuzH9ZhSE+gjGKgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:P+8Gfxvjmt2g5kk/SMrWhRltY/Xpw+VnwEw4bzUFdlLJvLhDBukzrlYvY6+2JplNVAFwT+EPLZTEo8vjRZcDCi7hMWzflnBy5luhodPhaadbkSVqYFAxp/tL2ca93wggzy+LrtkxZ6xHg+KPyq/CL4eLpGoogWLgiEmgoo3B/QA=,iv:Af7fU5oNaDHL3eIVFHj0V2HZp+5dcj5aZOtZTIt2rnk=,tag:1XRocH848g0tzySsgds+ig==,type:str]
  version: 3.13.3
