apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 4e4027f22d944614b2df0438e6358c6f6060b9b6
  name: harbor
spec:
  secretTemplates:
    - name: harbor-env
      stringData:
        CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:fLkkI5738vudhlzKX0PIWK3Y4ix+z9xXcsYWVBBOi7fQvYACg0SKAe5VlPSI1QrUof8bUjZkMCC4SCmngw2I3NwoYXEJvjCVTYMj3qoImx0230xxGY5fxucTkBkFKoRyaMG/3eDi4+/1gMRoXnohuWhNPb48MQQH5eX3LfGpSOpBcd2yowr19L0vvg0doqxLqVr4zf/8e2+HPYkSUtSrIte0o0K7fK+CM/D+laaoP7xVMNSIscbSVyrv3vh+6yoXerXDZtpCqqxzUGBfg3WVrLEr03DzI/j6Sm6WNhMP9NSEZDG07bIMohaPYhocPgmpU86RlDX3PJShVPjucUiX52n84wEstujhwuBx3Mv/RTsapOW4vb6g6IkCK07klH7kltDQUkOsqwoXpcy8JdQPPmZse+vBXFsHAHJY0cDwO61WbspMfKbhJK/fS+eOt+O67ojJ3cCjBqRlTH12FrD5QRKQ+pQ7H3xMLQO7trwX1RowwiY5kfZ3u7Df/kbkuaQevRHQALWxsKnjFhA7+8d81PArFqj1dA+i8Dt+O5lioovoEkVXVB/mB0brOF5TCK64IVHGoGXUVQ==,iv:TMaONSpI2mcRqalxV7Eu/eY2gB9s/DCWdT9RoSwJXgg=,tag:VEqsNylbu99/u2DyOdjgnQ==,type:str]
        CSRF_KEY: ENC[AES256_GCM,data:+E13+DjZeciCzoZ6t6jT9RcfWkqWmoY5lZP3GflaCsA=,iv:3lQPVcUu2Gdhu3HRoszyHKDJsMJx7UMAdoCA8uXcQqg=,tag:+LBCI/I03KTnmXzVMvQpSA==,type:str]
        HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:kCMMVLiWVhBg+g==,iv:FgNnaFHcEeff9z/1iKv1ZlXhwpHL1MdyhtddgD/0lUs=,tag:kkcK06NZjfYpSjeZKYrNcg==,type:str]
        JOBSERVICE_SECRET: ENC[AES256_GCM,data:1IdeB0mCOyOL/w4JpnH8Aw==,iv:PhBduXpVbgCQrVwgZcBsxayI1gvwp5V+y83lhqY2Rt4=,tag:TBZkTZqYQHClv+2NuGy0+w==,type:str]
        REGISTRY_HTPASSWD: ENC[AES256_GCM,data:lRCs1dwcNB26LqiPhLA071/5Wj9EwwHiYLicx6iVRqTqLdN+32s9RJkUrmCIC0bD4kwLtkAOGAIAY7IE+U5NvmeuMKa2QwGpW6a880++IFna,iv:junPIZYEyOXkr6RsSpUDiLP7XHVGoD4ualKplWdi8vg=,tag:DmalDudP1GcJCVBcYryYXQ==,type:str]
        REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:h+7Te9jcSoVYaSv6F/sojg==,iv:ZRNvBvBQPbo8OyYeqyblRu4Vxhq6Cdm43dDowufAzi0=,tag:eWZ+TnGjwGBnWrbq7yod0g==,type:str]
        REGISTRY_PASSWD: ENC[AES256_GCM,data:vHVnokWTQbc=,iv:qu08sMYkQiR8kk+IyD1UG3+wQjoIQ7YKV2DOenyri78=,tag:vUq9b4jvYMeGJumCxzaHMA==,type:str]
        secret: ENC[AES256_GCM,data:giFvseNNSHX17dRiUgL43A==,iv:avBuB5QB87g6DA8tEzrLghLDj2XicRFJk9/t4tmLIro=,tag:WC6jwyx7IjF5fci8PzsAGQ==,type:str]
    - name: minio-creds
      stringData:
        REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:UkYtfneNzg7YRqju/Mt2iAk=,iv:dDuMfBhA7O0Ny6jelUns1Rhh5/Sw1hsOt5XvXJkixXQ=,tag:qsfvDZr2V+AaXVtXTCBTOw==,type:str]
        REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:cATn+91U8KTnkM00q801SdoNnQV7Sr9+T0qJVTKwERhxbr6QgQEBUw==,iv:EyAM+owWQ3Jz+YAGZIf1350jP3XHSB8VQPHAO19Dd+s=,tag:Y0u9roL96uDgiBlJMQ0Ufw==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZUN4ZzFmTkd3d2gveE5q
        eERneUFzdnhJekc5ODdqUXNKNmhxbE4xUjBFCjB2VW9ueVpkcjVVa1dqb1pJK0dD
        SlVTMStobmx6cXBVVjVrOVlPeGFQYkUKLS0tIEFxQUNsVHdmSlJpMjd6OUNPZ0hI
        UzV2eldtRG5Sa2Q1MllNZlEwbE5qaFkKwu3uxXjOBtB6MCyA88H/ovgK5qoI6p03
        G5R0Y9+orymsXEAZSrkzafkJCqVv/pw3xk9JCFM3q9B7DIh5pkjLuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1umjsnzeel08tjeu5ye82v42suz5qhmcwm43x035gc75yyd8h5faqkmv4ew
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T12:41:38Z"
  mac: ENC[AES256_GCM,data:Vriw9t7VKWY4vNvPPX+myy7xrfp0fljzXo7+ye0PPT6PsJB0ERmTJaKrFUF4m2qv5RdjDube4wRbLcskZxHpdrRDuQtJp0imykHLzYY/NIouOzjAMu6ylhv0u2WzwOWfW87yiKASWW/naDG6tFXa4t0H2QqzMW5KBlW6gHhFVFM=,iv:jOwWdDiBX2QXfy3ib6w9+X6ctQh4tzKhoZpWAz1Y0V0=,tag:UCxF3i4ZXigaxuhUIQEC/Q==,type:str]
  version: 3.13.3
