apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - envs:
      - outline.env
    name: outline-env
  - files:
      - index.html=index.html
    name: outline-index
kind: Kustomization
resources:
  - app.yaml
  - ingress.yaml
  - outline-sops.yaml
  - postgres.yaml
  - redis.yaml
