apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 27c4e6ed4f5f4dfe89c1957a5ece05430bd45c2d
  name: outline
spec:
  secretTemplates:
    - name: outline-env
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jpUqyxHhW4zUupHdG5sUB05m,iv:R1kJXZDDejdYy2sKbi1WuR1NRfhuLQPb+Ybkw8Extqc=,tag:bN4WFlNPU35FYSmZdFqLXw==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BwiVkgNG83J/vku966XVcyu6T8QafIsItyoymxWLwY4g1B4fwsCmtQ==,iv:LX16IahvFI/5BKUi/9jNXQXTSSyuSrJ1mbTxh2kthTs=,tag:y1lWyPTmb+BZWY5hD3Cttg==,type:str]
        OIDC_CLIENT_ID: ENC[AES256_GCM,data:xa17paVumw==,iv:wTYqhj2F4b5SpFHLasjpGVBSwwEKhKIBbWjiyQUl56w=,tag:k5YPyBacr+qoz2wSwnjD/w==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xIOKuh+v5KScxg3+cCgH/LHnom4BAv/7xAZRupI4qKM=,iv:Jsf8wYhUpIJjJsYJG0nDI3IgTnfmw3IWenjWqb00tT0=,tag:F3sJmWu2IvGMRvrVZJcxpw==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:kTWhVYp8XR5oWoIqrn+RTeI9Wne9ZcERXqYcSCR2dYROBhvruuH9PPjKcbu3uyNOrMoXH8dZQtD5SvnUD4foyQ==,iv:MN0WZ8H39RrnZjHje2sT9gJRGXKdP9mM4oru1yEQxXk=,tag:m59UsJuSi2sVjVFfvB/lBA==,type:str]
        SMTP_PASSWORD: ""
        SMTP_USERNAME: ""
        UTILS_SECRET: ENC[AES256_GCM,data:4UQ2UKz5rCAA8K6USI46enmyw4MLZlwYhnhpD+/9IHftka1+GZdwHdXlOfxMZKiyqCq+3d9Kkk0oiZvrLKiWcg==,iv:zj5q89WfqERFkCeGBFfckE6Fee+3liOFiRM/bBInGzs=,tag:bZKknNtUdGkuafeOsH6XUg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbzFSeFRlbXk4d2dPUTd0
        OEMyN2dBL1dON3hZRDVqMzhVU2hvZWVsTUZrCm03MzgzdjFNVlhFTEFOdXc3UTVa
        MXlNWENCbWJrN3RhdTlpNVFpZTRpLzAKLS0tIDRKNWg0WGFzK1E1R3dtODBRMzhn
        MnR5Y0JveVZTWEl2Mmk2bGNmOUVJOGMKhx4mJtOuA1Kd4x1Zp/aBc4+CDWIquoVq
        tb9Zc2TjMk4JS2nWYJXVuoRLvVgBVlBTPhrR1mlTx+aRVa4o8OQz7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:09Z"
  mac: ENC[AES256_GCM,data:5RP0/WXWp2P8oFlFTsqQ/kgDl2QTUhZm4BP+7GulQEibXhoM93sZW6PjI7hDxP9zP7cLFjobIk8WbhL2Qsjp4fgIP6w2dJa+H3hxlD1IsC/7cKl1PXVXfJOd+2sY9WK8hUKGqYmGecKijBKP1xMOBjLO3wODKNGpUuFvQ8fyStQ=,iv:sD8Z9CiWHrqUQzprtSUBH0iXj6yvlZUKsvWdpvQ3/QY=,tag:4Q0w/y5g85qbuoNbnMlfxw==,type:str]
  version: 3.13.3
