apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 27c4e6ed4f5f4dfe89c1957a5ece05430bd45c2d
  name: outline
spec:
  secretTemplates:
    - name: outline-env
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q1nTS+vpHJXhxMwcxW+zQ+hp,iv:LUAWmfdDGIiOobi5HyNIEJ35WKrunyekKHzm+IWo4YI=,tag:8mcx4xvEW6NNFu6FgvfjiQ==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OgtZKJYcClfAs1LC74QehnbUW1KELaVzHW8yVzbULIU9CWG9VHF7Mw==,iv:4IjcIyV0tt+BBmJtD1GpbhSHl0vZn5pNhdEwMBoLWjg=,tag:pSSKorPAfzlcS6t9F0i8QQ==,type:str]
        OIDC_CLIENT_ID: ENC[AES256_GCM,data:UbVGOQccFQ==,iv:3btjY/otp8afT4ikYb9BgWTyMAxf1ekgjo1+8xz1FDE=,tag:ibHJghKDCXYHnrb/5kj+Yw==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:hjrYfJCkIVmW7ou2sKf7QKV2aQ/gN4mCopLeXzndM3I=,iv:BgOxheUlkcaaGWzfeV36LCPFOtqgaNsA7WEzSkOPOrY=,tag:ah12q1Yo+WYR60EFjmcAsA==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:ne3CasIeyCOpVkcFN/2tb6DtPLupK4VOybVrMXZ3soh8K4VWLNAT+Zt+0KufGimPutumjnAVhVP9ai3OHiC+vQ==,iv:73Y9Vb0DTA1UKq2fA3tgQtrAfolQp3SYeB7h0yu9nlE=,tag:lYQNWgVo3oAaurKQpN8QGA==,type:str]
        SMTP_PASSWORD: ""
        SMTP_USERNAME: ""
        UTILS_SECRET: ENC[AES256_GCM,data:65fHOwRE26K1kSDwpIeB1l8pXWcCNnhh7CZEdgeKvujqFusrYaxfeKAOUXT7VnvTNKwoD+s0F6vYbr6uhpAnHw==,iv:P1H/Goa5U+RNeIdhVQZP/l3EvIP+UUDniEWCOKLtPus=,tag:EOaHasQCMmuLgYtupOoGug==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuak9na3JZdUNFakRVYWhQ
        aXo0c3pUOXdXZDlMWkxQNlVBQ3h2ZzR6RmhNCjAyd2xkaytYRWVtMDlEaFduaHdu
        UWpxNllCTXVwajhPMU1tWmhoS1RHOEUKLS0tIGhRM0xBSTZUUVVUSVh6TkxKQSs4
        ZWcvbXhueGh2Y0N5MEVOUEI5QXZEQUkKENmgI56rx4JrKuTfteFBePARymVVs/kD
        C3WcNnua0+oqpXDJL6Z3Bn56EvhsFPXkBA8vt3eml6vOl0+bqYNe1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:2+5EGipbCb/uIr9Qr1NzBFZ1xH+qDqJe1l59ahMcvWDOY6BDzqzwuP8D9nuWQIAxY0k9EvBAYS9k/NBLJDlIKT4KxREdNXEWyfQ9+en5vsu1OFNNJzM0gm8vv7XPJRBTf/gZV2lK6P2Y59hgQBJijRYZrQL3xJNV99rzykeMSd0=,iv:a05ArYhEa6MjuMxuZ3IOpYLTG8on8Zi//keDNrkwrGA=,tag:9FiYmHj8sq5gEIfrpe8Fqg==,type:str]
  version: 3.13.3
