apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/cluster-tls
  labels:
    trust-bundle.ca-bundle: include
  name: cluster-ca
  namespace: default
