apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 610a57d8277a16c27055ef17163876ad28bbe31c
  name: ollama
spec:
  secretTemplates:
    - name: openwebui-env
      stringData:
        BYPASS_MODEL_ACCESS_CONTROL: ENC[AES256_GCM,data:Cv35Fg==,iv:24rJ9TYwMLDKTExV4Iwj9rs6Hk45OP6Z4ykq+Ngm8y4=,tag:lxmaTkPcYO7JPV6BlE26qw==,type:str]
        CORS_ALLOW_ORIGIN: ENC[AES256_GCM,data:7inf+rVlUrC74qc4WWgDHyG8JE1i77kcGh9T51iRfS2AEKzEKuQRGkVmSGOH040jipk8iOPCrBj3ixiy,iv:91wOO5YX0H8dBqdDDR0KpZPJjT7SdnpwEqTQzj5mwi4=,tag:FPcIP2oLR0hwMzf2zo+77w==,type:str]
        DEFAULT_MODELS: ENC[AES256_GCM,data:L/LXIV+euHeMEPc5/Gjcl6Ph5TRWGl/N7MNw,iv:PlxFyQDl0DVj/U3rZCqQFj1gmb94kdHGvWm/iZZ/VPQ=,tag:hctv4akMykKwUdy6wxKfEg==,type:str]
        ENABLE_LOGIN_FORM: ENC[AES256_GCM,data:cuyS2oU=,iv:OAszCtMT03Caj/3d9JudL3TLH+Pl7FknwZ2XaKMUpOM=,tag:C9AkYzYGC+Xi/0Nv45W/tg==,type:str]
        ENABLE_OAUTH_ROLE_MANAGEMENT: ENC[AES256_GCM,data:haGEAQ==,iv:dTvP8n/GfBMcuN/YT73Aby306rIohgNuOS4Cb+hWpaA=,tag:bMeCQkX2fKJkIiug6OThrQ==,type:str]
        ENABLE_OAUTH_SIGNUP: ENC[AES256_GCM,data:+IaCTw==,iv:4g/STd2Wiv2DTKAW8YzjeGkDtoRWof90geYQ4XG81ss=,tag:3LCQ1uLTse7vg/PNcv87uA==,type:str]
        ENABLE_OPENAI_API: ENC[AES256_GCM,data:Z/URtkQ=,iv:EC3ftL3nuwEPobsmGrP46ZOhlg7it3/SIE2ZsH6dn/I=,tag:J0oXRfjWBqp/gSiHrDZg9Q==,type:str]
        OAUTH_ADMIN_ROLES: ENC[AES256_GCM,data:df2rkhw=,iv:d+vqPmXcda4b+Fsd5r/QkMN7JBW1tcCVcJTtqrbIBbM=,tag:3+FdcpN6uyPB/pHeUDEXTg==,type:str]
        OAUTH_ALLOWED_ROLES: ENC[AES256_GCM,data:rUSX4rYpMLTyCQ==,iv:fjDWWgHk+MH1ubTaGAqO9xeLLSoqiCX2FsTf0Y6/VQQ=,tag:nHkkVkC8UdyWKkmldZGy+g==,type:str]
        OAUTH_CLIENT_ID: ENC[AES256_GCM,data:QasD9F/BpSy20A==,iv:NdOorqhUyQFc2WsBJxfnbfcNfJYYa5bm76v32Mm7j9w=,tag:0SgcLI2xEEmn6OuRqQbwng==,type:str]
        OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:9d0Ax0HqdaKWCdgpDqfNCb68IVTGpVEKAMP3GZa5DB8=,iv:w6G9H2LXwvrq/yb5Dmnaqh9xrRNtSjGw4mWndd+HqKg=,tag:LD2UqvS2FX8P3c8sxvFTDA==,type:str]
        OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:xvutfZ3k9R8=,iv:Dkr0rdtZ/vWOGo94wH1HghkaXG7X5U7HyLka+73K0nE=,tag:z1HwQ3FNk55GZZhpHuSwxA==,type:str]
        OAUTH_ROLES_CLAIM: ENC[AES256_GCM,data:v8nTDX7wGOmL7TP0FMiCHcstXbZ7Jr9DQVuBz6sljwk=,iv:ys6rVaJn4xw+HaT1w8iCp2bLpO2vY91lzDKNE+Sstps=,tag:L0ygU9G9m1KDBSJqoZZqsg==,type:str]
        OAUTH_SCOPES: ENC[AES256_GCM,data:lTsQ9RcwGbSV3IGq113cMcgF1dZTmX1SQAM=,iv:wjnVY2kuSBvQ5GvkXjvMCayJyy9K3ZDNeY3+NXQvqOE=,tag:a2NE/La2mVs4yIHF8qtyEw==,type:str]
        OAUTH_USERNAME_CLAIM: ENC[AES256_GCM,data:LVSMvd8Ug3de11UHuVUPhyWq,iv:Y1Sl37HMCAQKQRXGgZQq3F5AEW6ma3QfUmCi0QBnATM=,tag:t4MhdEQCEePyvOJY/QTXTA==,type:str]
        OLLAMA_BASE_URL: ENC[AES256_GCM,data:5oTGii6PBDvnnAMXiSPvNhYQFbPsWI0=,iv:AJmAZqo43B2bLfO36YSsVF+rLj9+3xHBcEa/9SaIe6k=,tag:VXADONbxOHw5TIOzTQJ6rQ==,type:str]
        OPENID_PROVIDER_URL: ENC[AES256_GCM,data:kNlrXkfrL8scT0Q42tJ70YowkKUDBQdEmERD695GedCOt0OqzQztk7jqbm/OGdoc64u+KVPhg48/dc7cgy3DMdGHl5rBwNUa9165sUs=,iv:4WgXkEMfnD0d/R/mN77rDYo6Nyjpq6bK9XVFxBsJzLo=,tag:/5cqv1kZRhN1vLwr/5RvZg==,type:str]
        OPENID_REDIRECT_URI: ENC[AES256_GCM,data:2MTcUkY2oFjcL2IlKkJbj9Izc8hgu6FjgrWNVWbI+fefTkrO5/XhuDksGBGwhLbcA9s8UIqV,iv:vTTkI4GNUTJY6eLunfCklI0/tAEXKkv5cQO0HiCTwsY=,tag:909cCAlE+pM/ZG1M3GvHPA==,type:str]
        RAG_EMBEDDING_ENGINE: ENC[AES256_GCM,data:8DuUAl6S,iv:g24tmuDGSliUI/BAbZLpv3tr4vqw2TANwnqfuzE4u5U=,tag:QXfexvN0J3dvGlR6Oqn3tw==,type:str]
        RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:X8+qPw4UO8T9N3MOOwD9u7CTJ+t+,iv:1PqVKgrhyBhAc0k301pdqPhWzmsWO47XWJK2iC9E0Fw=,tag:j/C8fSNunrJmg4VfkVjLVw==,type:str]
        USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS: ENC[AES256_GCM,data:+71TqQ==,iv:Fp8sR8vlHHjUJWn38GJKJIaGoNTHB56b3CsfYMYtb44=,tag:x3h9LEd6frNTUojE7uZmvA==,type:str]
        WEBUI_SESSION_COOKIE_SECURE: ENC[AES256_GCM,data:Uhs0Kg==,iv:V73b7hY+BBhM7HNoEsxuCjb8d8yVMl6dEBNsWzFv3Yc=,tag:bigzdwFm0aUNt6oQEsXU7Q==,type:str]
        WEBUI_URL: ENC[AES256_GCM,data:F8TnPA6O5spHxkeLCkh5yvN1q/m7UXKVyuNBzm3o5i5ngQ==,iv:xcU/cOV/xE/fkJvLvg2hO6ehRCmwbjJ24WqgL62DkqA=,tag:4T1EAPnW1KhPArGEaTtx8g==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOHJVdzg1aWg2NzlRcjNB
        UmsyYVhRbnBMQVhQU0NYK1FCZ2lOS3lIWlI4CjU0UERTbU00WmhoenFIUG1VU0VK
        dUdHYTdGbDY2ekxNdWZIT3JnL1ZZNXMKLS0tIFYwbFFkamlHbVllRnBDUlNxbTRG
        V2JsY01vVFkrdXVJREN2bzVaVndlRmMKEuENDQy3qCPIxFo1utvZTHBmyY1yBDoz
        613l1bThybqUNsdKvqbF5swLK808ix0VbkGYqNFifDIqUZmTPB4mWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:MNiSKq/ps8kd0LWBhc6fkw5H5pLupVgyYtlcGPMtzIHz74E21WO2hQuMf8HwYFJVFnr97TLZ0RlXE5TQ6CMEcnu5LSe53TB/1hFMnpmahDzoeIl7T3szJ9ZFwN7QU1yG8eGlPiROpFIVB27V7VpuHqc4zTqV7qmvHjidLdVLlFI=,iv:JhUC4+lVd5WweBpx9xeq5yCpa+kwV/alkgFYv/jzcuk=,tag:fKVOQfSAXLle7baJh2d0cQ==,type:str]
  version: 3.13.3
