apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../configs
configMapGenerator:
  - files:
      - default.conf=infralytics-cfe.conf
    name: infralytics-cfe-nginx-config
kind: Kustomization
resources:
  - docubuilder.yaml
  - illumina.yaml
  - infralytics-api.yaml
  - infralytics-cfe.yaml
  - irongate-api.yaml
  - latest-views.yaml
  - redis.yaml
  - static-content.yaml
