apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 7b3803df02de788d1cdba831aebf170d7bcdf085
  name: minio
spec:
  secretTemplates:
    - name: minio-argo-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:tyRxXafhcYDx3PKY1mEO,iv:9c5cv+E5zDX0p8IM9wWyAX87yAHXs3smimyx7hQC5mQ=,tag:/EJoCTr9FY10s/Q4t+LpkQ==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:X0aL9soKSfHH15n+ei3gLehhmRjv3xkpRKlkHf4HmUvM4XIJja+FCA==,iv:tFW+/p/cZn9J40P2KgLTvufMZ0qThvWCyeuyq3vT/58=,tag:Ln88BR7etA2s2rha8m/F3w==,type:str]
    - name: minio-gitea-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:3xL/dnBRaL4VHuo47sYofw==,iv:6zdQbdEuRWf0YXYRh8oGI4V7TyDaY8jsDYLjwgEeUcs=,tag:hjpNHPOrqOnA+HGjcbXpUw==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:y4CPE9tjKX5NUs+zoycn7v1qSEyGiOgr8qWKlHpg6hDhWSPJTMSZ6Q==,iv:kJ1kXOlyi40dHcLycgUxhJCuaokqsiVlD7S37iUaDx0=,tag:rVZE7GVUjF5seEx76RbCfA==,type:str]
    - name: minio-harbor-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:4ipNI0KgDhZPnX2XKNr6QOs=,iv:FDv8IVd9pRSRHqh3ConI+0Wa7eg2QxPqYFfAlfc/EVE=,tag:ERqvKE5fxFTtsp+5qP2N4g==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:pp9yjdTFutYpNMzcJXhOBzP7PlBDfxPlaD+Yxx+kTHO/OTwuCFgBxQ==,iv:TBQRme26xUNoltpM7Wv1Lgd4a1AIYMebSbx5P2YcY8U=,tag:RFmKx5e5ZlRTcIId8gkrlQ==,type:str]
    - name: minio-infralytics-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:QXQjId9qX3HUDOMmLShJ5IBrmV9VmA==,iv:sHxBRkkbH6FRod20odh0nHVpT/gRD295pNz2h8tGCNE=,tag:7MMJMAKedv3XyiCjWk7Urw==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:IvXO/w0h//LUs5zdPihwgrnHiQf2H5QWeZWS0Ib4SKxtP8BQTQo0TA==,iv:7j7QwiqGPD9kpDRK/owSit0pkk5uSlKJVSx5uotOtBE=,tag:qYrz5h4RtkAYSrM7xOVI2g==,type:str]
    - name: minio-outline-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:ihsncUDRvO7QW1RtmX7MnWA8,iv:utdX2B46AKiXXQzZvv/8DvwwS23x/EUpa16RPNtIT9U=,tag:8e9FPqI5tPJ9XczouUWB9g==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:LHu5zoQjk2+i1/8sAFa3K7pdRdMKcXTei0CB+YmIqe7c9Ukxn4KNeA==,iv:A0W+3OZ3HjfDh4VxVxlS6zjK8V9nfi327gWRpd6ZrZw=,tag:79z+6yRct2JHgVS7huhwUQ==,type:str]
    - name: minio-env-config
      stringData:
        config.env: ENC[AES256_GCM,data:V2t04IT40dU1Ptun+ei2CyDFdz0UCBGRNf/xbHD1n81dqoIP5+eqiaCLvN+/Qhg9RaZ1aW2BstQuLyfQRdg38erQ5/xTuU26V4+qBYMXoisxESxatgQ11PtJF63MeZDQnkM9RldeYxvhLAnA3Xbt1Ngd7iBeupIbSTZNrFKLHIVad8SrRkv8MJcGUYmv+onoOwI5z+vi4cs6/H0WLSXzXOLTjBFDp2IlJSUvCy27d9TNOpeSI0DQ1Pqm+zjoURPA8N1ZpMD7nvDWlbZPougOVSzIjqmXTBo4sSfo56/gDd4Wd777d4zdE1NSvplPfEKzUXLYKUengiq+HhP2DB0DK3l5rjD2CccGHnc3tJmFlfrBwUMXvvTB+lpJKA52HDMvBzGhlJ+nkEG8blw6ibSx+dlWk1py9lk/R0lp4LgHVpYHixWLIhQS0wU4Mpo6XfAYRrTal9CTjUXGJBX56d1Pro+Fj5AmK4rOR9koF/zoMd5wpSVA4PIYqT1jpvwf8ar8UTR0wQZ+DFLZVtBW/MhXxmgJo0NFUzZpX0TB2hU6igWcHbt8/Sm7eW+qgSiJta5hZu1v61R2OTjRHpU9NG/kuWkkFahVzPXTQVvGwEOKB2sSRfDqGsSDFcyZoRZQLhuWxfEkbvQe8KTht/1KXYo28p89AHK1tvXOw1zAhwJ3+A3hOTf4ZNyEbHsPBNP2d7X5ifyrECMFeT2EELhyBcrXVcU8Td+LXXTmtpoO3Fb5wHv3FwxgdNOOTjbDXLwqzYjeJESrnUzqpFxSXnTMDxqD7iYeJLGTBKpXGW/TyCuc2txenqPIEjlPYtPn7HQwC8XNHntKPl7Y8tyX/vodTbh+5PUPUB7iOc13Cqz5Mb/cd4hQNJ7ZzCn2Tp3GvlUjgfB9xgnCwdA5XkfxDAJ2bFS4vUnnqLb1Zzq9pZygYI+kq5+2wkRHozZHQ/1NjnUmzJJne543pBhsK/tst6Ggkxsvsg==,iv:+8ycBUrsNTKALWK3qrSAhhppd4T3A5ssojPYnvhd3MQ=,tag:u6fmcifFLUdQvqogCVLNwQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV0hBN1dKRHJ1YS9mVjgw
        S0xVS2l1QXpwdzhUUEQ2T1U5SnNtZUY0bFZvCmNuclF5N1M3WEZuNXg4NTlQZlov
        Ti8yQjhRZVJTVDMyWXVmYkxIREhHejQKLS0tIE4rZ1UwcVB2eXE4NTRiSFBSb1Zy
        U2dibUcrazBHc24xdjlnL1M5cVd4NjAKinFLKCMllwtKgoV5lh53OIU5jsvXUdXa
        UgsOtZ4gJMMVysElhiCpYBZCQgmfdvTUpeki2JRP0Co8bVbht4Go3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:08Z"
  mac: ENC[AES256_GCM,data:4jTVfqUfpR1mhXG9sEBiEzSU8WjCBtfvvzN1K9QKe/kJFgEsrY390sBkEhAY8Rm2BUc/9FqiL2/VisxOU8OqFFX/OV/Kre+xQU1Cd5Afx1j6yDISDKXjbYYWTI6xLBHzomsyBXjHu6gYRlCWMMnQOCXrq9rlN7tznhtnibSFDCg=,iv:L1/YtD8MV2OlsZB/+M2/VVDUYm8kknmsUMZe19r7MpA=,tag:1l7kkxdA3NKbonwvC+PigA==,type:str]
  version: 3.13.3
