apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 7b3803df02de788d1cdba831aebf170d7bcdf085
  name: minio
spec:
  secretTemplates:
    - name: minio-argo-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:ehGFBuVephz7k+TjrjmQ,iv:/9XjDE5ZP3qPI0HH/V+gLQwtGZ6RnDg6z3WCCqId9Zo=,tag:x3AUZjwLoXB0y/X+Tx2LJA==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:dRNz0kie7niB9P+F+n9FRqkteDvePLqfD9BtCMOjYxbQNZAy1RJ4uw==,iv:BkDGj2nPt7GUhQ7I/DVaGEjS3t7M3lXWKJJmlVVZfX0=,tag:/iVCllyG67vt4fPfYLqHzQ==,type:str]
    - name: minio-gitea-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:xoHhqZNqaJqe6n3W4sPqtA==,iv:qQS0FBwNow5oLhJlBwhLxjIoDkoJZ2ZsNIJUi6kH7ZQ=,tag:mDC7TTDt3BnIVVNnK3evBQ==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:J0QabxdiyMcsvdxgWSweGB23FqqcneN0PFQJ7AHqmRUXPz12XXgqEg==,iv:4wf8vYOT78pkpzK47Vq9aizY4EZiXH06lbF2sZV3EKs=,tag:FTAI4yMC6yCCNjJKKsaFWA==,type:str]
    - name: minio-harbor-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:xRjGwHbY+j6hn9yr80bUS+M=,iv:AciPQAyDHns5qPoWFxM+tq0F/4UCX0wwsMzUMgYUOrE=,tag:Jev6zDwfPST3crRmuFpzIw==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:u8DzBdMCDSozVLxVLHQICLEIDbpshIS2W45T8BFVEMaOR/KsuMo5fQ==,iv:XGItyDv+3R2YkhC4h9FglQICk6rjCohAS7hCxsxQbsM=,tag:/xw7n91yAegFfkxvc56gJw==,type:str]
    - name: minio-infralytics-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:6i038boLk2QH2EUXj8JB/L+WSvsSGA==,iv:paLLQzlN/0ov3QQYLA2PokLSwWf6dXNoaKHa/2dkVw0=,tag:7TH1xu+SXw1q5H6UiEzNGg==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:VkBcbnZWdyG8gUP01wvYHtY49jwc+X8dPXlC7BocBbzLcY/zNo3beQ==,iv:/F53OjDDnrHLINkNc+hrQTSnp6TNHprXZmYqzQ7kXNo=,tag:Cn08UFbJicvrFqmTc0ZONg==,type:str]
    - name: minio-outline-user
      stringData:
        CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:0ledPqQrosZsnIqWrdCt/xtW,iv:oMYcgI/moGG1CRYNp/HJioEm2IPx6Mjnpc+ECstVbXs=,tag:JVqmyYG6LfZ5LsSd2wfIfw==,type:str]
        CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:1qqup/O+/WANfAqKzt0tCxc8yCx4M1TuiNgMmefguucgl3d+0WoWZQ==,iv:uMduYyBpftNUwK/0WbOMAQKQm88IVwR4wBE6N97fmGI=,tag:8f6xxINbUsw7dUyFyP3seg==,type:str]
    - name: minio-env-config
      stringData:
        config.env: ENC[AES256_GCM,data:TVuK843sQlueIFA5nFfFzL462QLcAHLyjoqTLw9WBthhTwNO89pRlDl2iqfBgsaSJprpbaPT/wLVXidNqDemHMnqumwuf7r60C4hnUxKyo+9935tyDqxjiMvv1EL/p6syDghZKIgxV+7OoNZ2Ou8QfDRoE1GwSHH9hQD2KdNHtAs8Wswyc/ZA7EVE1NWlaCHWaZyaBsQyRwWBJ1mpKn3fcTAURfWF93oMFVrdtYCx12HPIOnoD2fSZo0LvrYrQ10KvRy6loL331ehwvJ6FVAk5Q+QCL53jj3IkrjfA6q7FFRR/UKTp4YHnHClMP9KENAwuXLIK6dDp9l1MDwCzZMU5YvZYMlYHi8QVR/60OKeD5C8KgGl/1bxT2wA0f2YBDF0+L8EBM0NV86pmMO0Jv7ibNuzwg7A8OtjQv90P2+22pjH8Ex05x58VixQ7NBr5vjB+4y3SOkNicUv55AK38BO0KbqeAU/nWZ4uSqGfMmjCt0GY1YzMiQ1cBrRajeRN3co9tbmSx6mYoqofhiMe+60QeF4HoGHvbn70tj28lVHR97Vj0ghE8k9xF04nKq7dEYCDPRC7ghwGpcLysqwJAkc0BOFR4KMGP9SERvJ9//5Q3gbsJYCkuNa7uQdfiiMjI13OWYEFt3ipsyoZI7CW6CHDg0I+d+9mWghQG8ohnWC3d0eUMb6FlcqgdErqPR3kojFjI2DTtdO+excyndNoNMSg2tbNPAtpk4ba+8FbINzZ8ROlURGlfegAoSYK9vfSQnVr1Z0NA4oMtUNPh1g4RI8Zes34PF5y4ll0dLNbMeKI011oJsnKtOpqhEtfT8e7Y0/MbMY8Sp2Dr6SN+qfeZzlPIJYXJkmv1/hIHnZw5SsAqbk8PcS60bshwm+/TQT0BtkRx50qXGQfSaZIgSEOMVWdhFNPa7s2FqPTAjNm+YbVumDwU1ecS4dwBVqVjCamsrIGIsqAeFBxfFFC08r5brRg==,iv:KXfX9v1/NO8T2jXoy8FAtSh/ZL7024G6VA6q6OB7po0=,tag:9kgI9fZhp4s2quFE6YR0hw==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjNXMlMwNEs0MWdUN1FF
        akRRbkVrd2R5SVRZUFJEa0NlejlBNGw5VlQwCnFJNmtoVDVTUDB4MURJOTgxZFpm
        dzB2M3l1NTdWS0hDaG1DRGVuYXpNMHMKLS0tIDE0enFYTlRtcEN4VzJEeTFweXB3
        eHdlMkZwOTNleHJqdHVnMUl6Q1N3OFEKFVEp8hrEIUagp5jMj3tr1GEZJr/XwSIf
        dWVc62EznoKEmHaglu47e7rAKoefVKHqaaZkXvJWptUGOBTFIDZRvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:HBr/YKtLxMm47CqDdrn5f25YQmfGrNCifL9wlQ+XAR8Hc0XpciP+ERlQfSGPdkvDZJa+E1i5vWpowVRfxLpX09+oWMclpyJFZdxnQkOZluKt7Al0LyJ9Co+tHlJLppjhgNwGJhGsJdYtPkqbwsKLllWz9+sdpd4tqjiJ+zC+LCo=,iv:p7L4XVifcc0CXfBQXzu6Xo5X0XvxjrqAx2+qoR/Jgo4=,tag:3QEr8ln2Hmm7z0q50jHdTQ==,type:str]
  version: 3.13.3
