apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: d7bfc4d555d25f43f3ecf7fd38129073dd116117
  name: infralytics-collectors
spec:
  secretTemplates:
    - name: infralytics-mongodb-config
      stringData:
        config.json: ENC[AES256_GCM,data:LwCmx+//5zcLrCrnhb87qYcXPrVeJzPXuSBk3AP5ILIDvwQT9kK1lWf4oryX76cvoTXHZ6yas+nOVtTU/uB/MKqMggwRgEdWvBh+e8oiGsZz1kWPZJE0KQZaRZbVCELcXjtVbyxE51ysGSCKcyH/ud67hjEFvjmLNyvtCWxRA4GpASHlijVb+rQB9pmUjPXzyjoD3n1mDHU7bUSpQkN6IKfxmEnBl7VNpwuIhqV8uW2VI4bN5hKoJnJIvDWWZj2vQzw/qQeXR4mXv6T7veeZ3jSxzkRM76vErjWclL2cPhWaIXn2c3woEzUtvKXfM8UOByRnvGsg70AD1R6IYBEcvtRjB3PE9IMCY7pyZa/dUZAOopFbD3pp+bKO99SQhvI18b0Oerey+vQcnUdnFFu1BW1KpUwWS0UoYzFEI1dBV11I5HuInizFPpSejiTkxrieJCpWDHYG4dh0Ng==,iv:kwAUBu5bNkMHs19Z7bZIwDAfMUAaPyYglnV3G8PBV90=,tag:CM0UmA8WvWCqF4+APouJXg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRGl3VEpQTzVEakh4SVdw
        UnZMOEVWUlBvR2YyQk5FNnJ1dlFDYUdnY1dvClhuSUxKb2tjR1d1NG1BcVg3OHhI
        bU5oWGpMMkdNaklqQ3pzMVpydXk0alkKLS0tIFBFb043ZFVVbUhoemdwYmpFMGVP
        Q2ZJUy9rMGNhcmlqWGw2NEhUMzY0NjQKWZBLVOsgY/dSTDC2w6N/i2XgwtEoRzKi
        XP/OvKjBxSY919GxoNzRenvR08Sh4VZVugm+qfgyKF2plCHmgXU3AA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:p+/S3O/s7ZaQ6fIoJ63zRZHVbhq8nHhuLwIJnnskr3dR4/EOg3JDd/lFw33h8OIUU8bhSp2pkFj7B1hE2bcERNKZFHPzmwLSJbKnzHczNo9F/e7DdIlrUBSBj5UjKiB/bVSdaJEiGotCnmma2/PWNEJECyK/cDk4NvKFcLcom4U=,iv:r25bg29ia6+r33aDfB6alF38LE+Bl/nVRjRlHZQPPLw=,tag:+COTWfbTcnFDKmDaybj8Fg==,type:str]
  version: 3.13.3
