apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 5004fe2ac3abc1a8cb897cc2005d16002d7aea71
  name: cert-manager-extras
spec:
  secretTemplates:
    - name: cloudflare-api-token
      stringData:
        api-token: ENC[AES256_GCM,data:98a7hhkJSFcJFD3wCkgmTIxtX6RahgCBwfAnA3xa0v0Rxj5bu0LE2NpDIsgyE4uHiyrscxc=,iv:U+3tmLH7IHc1+kBiHGFcOXBuZwmXnCsBfBDqSDwANj4=,tag:Sc7QLdwFqFUrAequW4MxvQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeCtKMC9zbDJyY0hzTEFT
        c3VpNWxicU9zWXN0bWpoRHlNR3dWNmh1STBZCmZtYndwMEJQcERMcHZpdVZRaGVi
        Z3dsODBLTmJPYUEvcnVNZzFnZkZCTnMKLS0tIHZodFkzVHZWbWprZCs1UXY1SEEw
        ajk3YjI3aUUrMmgvSW5DeWFhNTRqSDQKEQO78P9hYeJa7YQpe+fnJ13nQe1IeM/s
        q8HeKn261pXBU/8EAk42WbaIJwRNLGt767KaWAk+QGum1rHsy08OWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gf6fxcc2wk03y5p0hrv0wgww2m6xq0mc8ts6390rwdcs0mlqka6qau7r52
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T00:33:09Z"
  mac: ENC[AES256_GCM,data:I8ufQLQdWvgVPkoRYetudFjMn9toAiNDe95RvI/CkfI0aLFNgal2d/a4baDE0TeSelHHlK8xUQVO+dhdLbmJIThcf2GcFTNSih6wCrYfAFEi1wqgSEqSKBJdC+ZukQ6HKhlNQcoKHmSssfsOdj8EJv1YmTBTk1hrMcXIllJruyo=,iv:e5901okELh3W/6wqpmNxirOyfMSNZSr6LzssXH7+1+g=,tag:wsbidoq9zil0RwfydDmC6w==,type:str]
  version: 3.13.3
