apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 5004fe2ac3abc1a8cb897cc2005d16002d7aea71
  name: cert-manager-extras
spec:
  secretTemplates:
    - name: cloudflare-api-token
      stringData:
        api-token: ENC[AES256_GCM,data:5VsievpEbPFEox7V9F+M9/L09P2VQ4QJA5rnRHhj8/eMRgPuJ3VUx9foiAKAOYegV0TYdVM=,iv:2/y97w0XvChU3pKfNdafbzHYzRRwRZtJSzEpED9WYvM=,tag:KkxJ64o/eOpDzhbmawKEAQ==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RGU3MklobkZKSXJ0UEcv
        SmRUU1drY1lFR2VKZ2RxakZRTVZ2SDF5U0RFCnR3MnlCeEliMlFJWjdjM2lXaDVC
        dkVSWG9hMVNvb0RLb2JlcDBXb2wxUE0KLS0tIFV4czdYYi9oYTg2cGtXZHdEVGhY
        TWVJaGdJS3RVZDJtQWdORDV5R3dOdEUK8cpzunI/wA96qATekSjlKgpW106zNvYQ
        06i7+VBdLEb5t2V+wuOw8TXNt0sVsSApFg+z8dW3QkbOyRm7Sca1Eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13rl9kyy5eu4yy8qrqlgrw5n8wtvtzslcuea6l7wc60l98lzrnu5s0qddr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T17:27:15Z"
  mac: ENC[AES256_GCM,data:uwkpX0uKStWuU9gcsCazHDGjE51aggp4nydDOqfL+tolS8e41joh511aSGlgSJaKsUZ1efoPaQqtONzwwIxMxEngSZnP66QW4iheshcTJ8Q53yeDtJscXyF1kCGMD2As6/0XVa2QpZRyUveWksSBV78hNal/BRa8SLr56szts/o=,iv:C8VSIaA0LvHbYngtl1OSOgNBKiI7Yspa4mgW9Je2uMA=,tag:WrKBfziKIFFRgDXxfwbocw==,type:str]
  version: 3.13.3
