apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    decrypted-sha1: 5004fe2ac3abc1a8cb897cc2005d16002d7aea71
  name: cert-manager-extras
spec:
  secretTemplates:
    - name: cloudflare-api-token
      stringData:
        api-token: ENC[AES256_GCM,data:dAHMGNGUAo2LlgHauDogy/aN/A8w/RLuWW6znDh8bXJMJyWlfy1JYlMoPtkp5q2O78ELKHU=,iv:lbJGV7qIO0SRK49TkJAbPX5JQpQE7mnQRvZfjKVgLCE=,tag:L8lZBD6BlZPgWGd0MPDNbg==,type:str]
  suspend: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UXk5TkhETnlFM3h4YVBE
        V3dKZDFlb04rd0FoUkd5cnNCcE1tSDNBVGpnCkRMblB6cXROMVk4RFlFUDFNRXNw
        ZWZhMm5DUGZVdzZVZXgyZHFGbmx1YWcKLS0tIDF2K1Nic2hVeFRiS2RjdGlqM3lC
        aGl3OGZqMVppaUVLbUlCZjlYVEFGQzAKr6/n/mSFKV5fK5WyQFb2EK7tQ4YONZae
        9QwOzMbF/AzKqfiYDxPzUr/v9kuX7LTjpSqxVjmrfZwMhMA8g4Expg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1umjsnzeel08tjeu5ye82v42suz5qhmcwm43x035gc75yyd8h5faqkmv4ew
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T12:41:38Z"
  mac: ENC[AES256_GCM,data:cpcOiOtdx+aM9PK1DtGT37PdLJZ7MTeS3p3HrDqLukCzOWIt1Ns7FBCScOodMnP+/AyjjQzdyFyBPfjh+lVmjbnAOkwoOTP2N2v5bgyu7KLuTGy8SBKP4oaj/rwJk0D98i0kEyakePCN0eG+Zd1NQsKb9NU/h/2ZNJLtduP6Nlw=,iv:jNp/wi9C6/lJrqWL5RjB68PE2NDYd9KLdBR14soQnJY=,tag:gjD1q9ZC9KRURlJT/SOSgA==,type:str]
  version: 3.13.3
