apiVersion: v1
kind: Secret
metadata:
  name: client-ca
  namespace: default
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFTTCCAzWgAwIBAgIUHj8bYVBXaFC/J7OLsRdeohZWdTcwDQYJKoZIhvcNAQEM
    BQAwNjELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB0RldmFsZXgxFTATBgNVBAMMDExh
    bmRvIFN5c3RlbTAeFw0yNTAxMDkxNzE2NTVaFw0zNTAxMDcxNzE2NTVaMDYxCzAJ
    BgNVBAYTAlVTMRAwDgYDVQQKDAdEZXZhbGV4MRUwEwYDVQQDDAxMYW5kbyBTeXN0
    ZW0wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCqYA4uEAQnc+4LZjKm
    k6DOdwwMoDGERFO0LbMCdswuBS4gAIz3csZ6u0uEmooN61cOGNPATJECTzY/ifDx
    rB2iawmaUTCdtDi/QaFwSJauinCFclF5VX8h3n0owl2OZDnHl0zPOwwNuQEztl1f
    P9d6Cbeb1tUVj4hjkBsro3mra4IS7UGK+n1+tWu+X6gS1T9IgnMtU4k2U23qOTvY
    8CGNmqHZB0LvycZIwuHZDft3SGBruF3b2sZQf9qj17KL3xNJkspuEK6tuWOet6AU
    X0Vw6KyApBH6ycM/A/01Ku7SbB2y3ZRiXZs+2F0WQLui/SYbXRgr+MejACcz6yXm
    aG9HntwijouwSXnGkQ9wKHT0X1odYYhxALlvloPhoecDxJYP4L0aOZPjaAKyKE0W
    BG/vS/Z2ugWbOpmzJ6sU0j4S2T6mUQ7Mt+aDd3CNHTa2ZHH65xwA60mskljXtcn3
    uvaxCoQCoWlliiGjML8AHgFC1KEI38/VvEbxyH67hq32sw2teOH5ovUN6epPARky
    Gh48Ndes2E+dQynVSaE0/AdoFm/1gmivCZzJv4t91hdu9pdmq3hMy/k21RuBPKUv
    u7S2zb6VlmIBHxOixLXLvGrXA+sHrnQgLQ8uq2DkSgHeCVhQlo4FljDbXKq9A/sY
    gYgGqlQdIN3A5EUbWRarvjuZ8wIDAQABo1MwUTAdBgNVHQ4EFgQUIZxmJN+MHfcm
    TddZTD6QpA9KPfYwHwYDVR0jBBgwFoAUIZxmJN+MHfcmTddZTD6QpA9KPfYwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQwFAAOCAgEAJQYFg+Bs7QYeJ2GQsQCR
    GOiQhHkOJrOVgwsjHUHzFbIjwnqnoYV4buUrLcpSpaSRGtwkGy4QrLo4QwOR0yCh
    vC+sFtwHDsy5IZ2tBl9llmW1cgFtnth+PN//Ny0JgOofCLpmZcRj6nGds+PGySJX
    goUnzt/F8sr9xJzGCiVR0wH8fyx2Mvg0rLHDTcf6SdNus7VRPG0MCD+6bGQza8QS
    FTl/gOiLXR+Y9c8MB6PF+0XjczW7W3iJHHVXu1yliEjt/rGsA8sjPlCLMeFHhnPv
    4pRV30RitdiYF7b/Ny6YY/4LfcIrq8+99vF4hpLuIN3u8Ptyyt9PjJhpV92iWGfh
    0Y/djfze5PgUCUZWuFqXXFdN4V9SVw1VPswJokyC/VDjQJaPROT1WLmSx/vS91tq
    DVFg1l4YJp9ZNGcoV0o1Ynoge8dMZcnO3OGnzjRlurjhFiSe/TdgPCEiZ2oR0FYy
    6/KAXqarcbS5i/UdiClW4sr9/IcQ16AtSn53RNtZZWjCFvmN3NmW6M/0ENt4sN58
    Mt8EKcXUTQnUWIePRD/IFtIuDH+SQ4TpT7PaVxGC6D4zyv+rNbvoVtBddLHXEmX1
    vCmerYcMhQX+FpN9RSPdbC8ZcogYCljSCExO/Db6SaF0pwtuR0gD2wjZ01b9CEqk
    lDQdr1YUxdmrmdP1wqst70U=
    -----END CERTIFICATE-----
